### ISSUE TITLE
Category page Sidebar issue 

### ISSUE THREAD

**Issue by minankmori** [bigcommerce/cornerstone#1000]
Hello,

We have noticed one issue with cornerstone theme category page.
When any category has no subcategories and shop by price filter available in the left sidebar. category products right bar section will be moved to the left side and show white space on the right sidebar.
Please check the issue on attach screenshot.
![2017-04-26_2021](https://cloud.githubusercontent.com/assets/26482645/25440764/02f38828-2abe-11e7-8c70-0af23c33485c.png)

You can fix this issue by adding more condition on the sidebar so when sidebar has no section available you can make the category products section full width and show 4 products per row to fill that white space.

Thanks,
Minank Mori

**Comment by sacr3dc0w** [comment]
Using the {{or}} operator made for a very simple solution. 👍

**Comment by sacr3dc0w** [comment]
#1001 didn't consider 'shop by price', #1018 does.

**Comment by PreciselyAlyss** [comment]
Closing based on @sacr3dc0w's fixes. Please re-open if necessary.
