### ISSUE TITLE
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOD'

### ISSUE THREAD

**Issue by martinmckenna** [bigcommerce/cornerstone#1004]
### Steps to reproduce behavior
While developing on stencil cornerstone theme, I can't save the config.json file without being thrown this error Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOD'

This is from a clean install of the theme. Followed all the installation documentation correctly.

e: Okay I can save it, but I always have to save a second time after the error is thrown in the CLI

**Comment by mcampa** [comment]
I tried running `$ stencil start` and modifying `config.json` file with no problem.

Only if I have a syntax error in my file I get that error, which is expected.

You should see an error message like this, that explain where the syntax error is
![image](https://cloud.githubusercontent.com/assets/1934727/25717762/585e2fa2-30b8-11e7-838a-fb31f75b6911.png)

**Comment by martinmckenna** [comment]
yeah but the issue is that the out-of-the-box config file throws a syntax error.

**Comment by mcampa** [comment]
This is really weird. Is not happening in my local environment. 
Can you tell me what OS, node version, and stencil-cli version you are using?

**Comment by martinmckenna** [comment]
Just did another install and now I'm not getting this error. The only different thing I did this time was call npm install once instead of twice like I did last time. Weird.

Anyway, I'm using:
Node: 4.6.1
Windows 7
Stencil cli 1.9.1

**Comment by mcampa** [comment]
I tested with Windows and node 4.6.1 and still cannot reproduce the issue.

What editor are you using? Can you try a different one?

**Comment by martinmckenna** [comment]
Hmm. I was getting this issue in VSCode, but not Visual Studio

Weird. I don't think I have any formatting plugins on VSCode that would affect the json though
