### ISSUE TITLE
Javascript PageClass for custom page

### ISSUE THREAD

**Issue by ovsokolov** [bigcommerce/cornerstone#1011]
### Expected behavior
PageClasses should be attached as configured in app.js file

### Actual behavior
For custom pages not loading associated class

### Steps to reproduce behavior
We created custom page as in 
https://stencil.bigcommerce.com/docs/authoring-custom-templates 
add page in customLayouts -> page 
So far so good - page displayed. 

Now we want to add script to this page and trying to follow 
https://stencil.bigcommerce.com/docs/js-101 
Created custom. js file export our object and assign this to new page 
in PageClasses. 
That part is not working. 

Loks like its issue with window.stencilBootstrap . For existing pages like Blog it loads PageClass as the PageClass class attached to it (Blog), but for custom pages it always loads as Page class

**Comment by PreciselyAlyss** [comment]
@ovsokolov I believe this issue has been resolved. If necessary, please re-open this issue.
