### ISSUE TITLE
Styling for checkout page (Checkout Type: One-page checkout (Recommended)).

### ISSUE THREAD

**Issue by ocvninfo** [bigcommerce/cornerstone#1013]
Today, I noticed that checkout page doesn't showing any changes when i editing in the **checkout.css** file.
It still showing styles of the Big Commerce.
I have view source code then i see **`<link href="/stencil/theme/1/css/checkout.css" type="text/css" rel="stylesheet">`** but this file is empty.
Is there a way to fix this?

**Comment by PreciselyAlyss** [comment]
If you are using Stencil, the file should be `.scss` Can you verify that that is what you are editing? 
The resulting output will be `checkout.css`.

**Comment by PreciselyAlyss** [comment]
Closing. Please reopen if this is still an issue, @ocvninfo

**Comment by ocvninfo** [comment]
@PreciselyAlyss My checkout css is still not working.
Please see this screenshot: 
![image](https://user-images.githubusercontent.com/3072481/28909343-52035aa6-7852-11e7-947d-37673bc08256.png)

**Comment by mcampa** [comment]
@ocvninfo Make sure you have the scss file in `assets/scss/checkout.scss`

**Comment by ocvninfo** [comment]
@mcampa Yes, i have it. I have tested on cornerstone theme and still having same issue. So i can't css for my checkout page.

**Comment by ocvninfo** [comment]
Please help!!!
**checkout.css** file still cannot be applied on localhost. But it work if i editing online with Edit Theme File.
