### ISSUE TITLE
Random alert boxes showing up on home page. 

### ISSUE THREAD

**Issue by abrambailey** [bigcommerce/cornerstone#1027]
We haven't done anything to modify this behavior. This is happening randomly.

![image](https://user-images.githubusercontent.com/978462/27345156-49652008-55ae-11e7-9083-45c5ee89170a.png)

**Comment by PreciselyAlyss** [comment]
@abrambailey It would be helpful to see the code in order to provide any assistance. Are you possibly using banners in your store?

**Comment by bc-zoharmuzafi** [comment]
@abrambailey I see previous response and I would like to ask if this is still an issue?
