### ISSUE TITLE
Specs Tab

### ISSUE THREAD

**Issue by thetechie92** [bigcommerce/cornerstone#1065]
Just` a crazy idea I did if people are interested for their stuff as well. You can take the product.custom_fields and turn it into a specs tab for your site.

...
`{{#if product.custom_fields}}`
`<li class="tab">`
    `<a class="tab-title" href="#tab-spec">Specifications</a>`
    `</li>`
`{{/if}}`
...
`{{#if product.custom_fields}}`
`<div class="tab-content" id="tab-spec">`
    `<dl class="productView-info">`
           ` {{#each product.custom_fields}}`
                    `<p><b>{{name}}</b> {{{value}}}</p>`
               `{{/each}}`
    `</dl>   `         
`</div>{{/if}}`

**Comment by Ubersmake** [comment]
Closing this issue. This feature request is something we've talked about internally, but the delay is in figuring out both design and UX we're happy with for the majority of BC merchants. #1295 took it one step further, and that PR provides a great custom implementation of this feature.

**Comment by sacr3dc0w** [comment]
@thetechie92 #1480
