### ISSUE TITLE
submit button send an email to email address

### ISSUE THREAD

**Issue by patelbj3** [bigcommerce/cornerstone#1072]
I am a web developer / programmer. I am currently converting our website from blueprint to stencil.  I am trying to add a custom page with a custom Form  and add the php file, so it will generate an email with the form inputs upon form submission.  I don’t want to use a third party company.    Can you please let me know where should I put the php file in Stencil CLI, so it would work with our new Stencil theme.

**Comment by mcampa** [comment]
You can not run php within Stencil

If you want to add a new form page you can create a new content page in the control panel and add plain HTML

![html-content](https://user-images.githubusercontent.com/1934727/29578859-ac0f75f2-8725-11e7-9e69-c5a4c6f8a32e.gif)

**Comment by patelbj3** [comment]
I am trying to create the page with submit button so when customer fill form and click on submit button I can get the form detail in my email so can you please help me how to create that submit button in form which can provide me filled from by customer.

Please do needfull

Thank you

**Comment by PreciselyAlyss** [comment]
@patelbj3 You can do that with javascript. 

https://stackoverflow.com/questions/13611614/submit-the-form-using-ajax
