### ISSUE TITLE
Featured Products causing significant slow-down in page load times

### ISSUE THREAD

**Issue by jeffhannes** [bigcommerce/cornerstone#1075]
### Expected behavior
In the past (as of last week), even having 500+ Featured Products did not cause a significant drain on the system; our homepage load was still taking 1-2 seconds.

### Actual behavior
Presumably due to some change in the stencil Featured Products and either the amount of information being pulled for Featured Products, or the way in which that information is being pulled from the database, we experienced a MASSIVE slow-down on Monday, where it would take 12-15 seconds for our homepage to load.

### Steps to reproduce behavior
Add a significant number (300+) of Featured Products to the homepage, and you should be able to see a big slow-down on page load speed. For the time being we've cut our total Featured Products, but this limitation and temporary solution does not support our business model.

Something changed between last week and this week, and it's having a SIGNIFICANT impact on bandwidth.

**Comment by bc-zoharmuzafi** [comment]
@jeffhannes we changed the query to fetch this data a while ago. It doesn't seems to be an issue anymore. Do you experience any slowdowns still?

**Comment by jeffhannes** [comment]
Seems to be better now, though we've gotten used to a smaller number of products. I'm glad you responded to this (albeit nearly two years later) as it gave me a good reminder to undo the jury-rigged solution we'd had in place where featured products were being loaded via an ajax call.
