### ISSUE TITLE
Does AMP feature work?

### ISSUE THREAD

**Issue by kruny1001** [bigcommerce/cornerstone#1076]
I added amp analytics ID which obtained from google analytics and I tested a product detail page by using https://search.google.com/test/amp

It seems not working properly any idea?

**Comment by mcampa** [comment]
You need to provide more information. 

What changes did you make?
Is your store in the beta for AMP?
How are you testing them?

**Comment by bookernath** [comment]
Hi @kruny1001 , AMP needs to be explicitly enabled for your store as part of the BigCommerce AMP beta (it's not generally available for all stores).

Once enabled, and only if you're using the Cornerstone theme, you'll be able to view an alternate AMP version of your page by pre-pending /amp/ in the path.

So if your normal product page URL is domain.com/product, the AMP page will be at domain.com/amp/product. It should also work for category pages.

**Comment by junedkazi** [comment]
AMP is available across all stores so I am going to close this ticket.
