### ISSUE TITLE
reCaptcha appending to footer?

### ISSUE THREAD

**Issue by PeteyRev** [bigcommerce/cornerstone#1086]
![recapthajs](https://user-images.githubusercontent.com/5169882/30498334-e27cae4e-9a1b-11e7-9c29-d766c47becba.png)
Hi, I am using version 1.8.1 and I have noticed in my network tab that the reCaptcha scripts are being loaded twice on my product pages - I see that its being called in the `{{{head.scripts}}}` tag - one is in the reviews modal - and then one that is appended to the footer which for the life of me I cant figure out whats injecting it there. I am unsure if this is fixed on a newer version, but right now I can't just completely re-customize my theme, could you assist me in where/if that change was made on the newest version?

### Steps to reproduce behavior

https://www.upliftdesk.com/stand-up-desk-with-bamboo-top/

**Comment by junedkazi** [comment]
@PeteyRev thanks for reporting this issue. We load the script only once by loading https://www.google.com/recaptcha/api.js in the head. You can confirm this as well just looking at the page source once the page has loaded.

https://www.google.com/recaptcha/api.js internally calls https://www.gstatic.com/recaptcha/api2/r20170913120556/recaptcha__en.js which loads the script for the first time. But the remaining instance of the script being loaded happens internal the google recaptcha. Follow the initiator tab to understand when it is being called.

I hope that answers your question.

**Comment by PeteyRev** [comment]
@junedkazi thanks for responding. Yes I see that, but its actually being called a third time - I think my initial message was unclear. https://www.google.com/recaptcha/api.js initially calls, then its called within the google recapthca iframe, but then I am seeing it yet again at the bottom for the footer, like its being appended there. So three times in all

![9-15-2017 4-50-46 pm](https://user-images.githubusercontent.com/5169882/30504731-11a8ea42-9a36-11e7-974d-c0761c2fe28a.png)

**Comment by junedkazi** [comment]
@PeteyRev even that is being loaded by google recaptcha. Check this fiddle script https://jsfiddle.net/5vv5gmdz/ just replace the "data-sitekey" & see the page source

**Comment by PeteyRev** [comment]
@junedkazi thanks for the clarification. It looked like the same code at first glance which is why I thought it was duplicate. Thanks!
