### ISSUE TITLE
Origin of <amp-iframe> must not be equal to container  

### ISSUE THREAD

**Issue by abrambailey** [bigcommerce/cornerstone#1103]
This error occurs in the product page and prohibits the product options from displaying, meaning the product options cannot be set, and a huge blank space is displayed where the product options should be shown. Please see https://stackoverflow.com/questions/37319557/amp-origin-of-amp-iframe-must-not-be-equal-to-container

**Comment by bookernath** [comment]
Hi @abrambailey.

I suspect you are trying to view the AMP page directly on your domain like this:

https://bc-amp.website/amp/fog-linen-chambray-towel-beige-stripe/

This is not a supported way to use BC's AMP feature.

Right now we only support being viewed from the AMP CDN, which is what will display your page when it's viewed from a Google search result.

You can preview and debug your site using an AMP CDN URL like this:

https://cdn.ampproject.org/c/s/bc-amp.website/amp/fog-linen-chambray-towel-beige-stripe/

**Comment by PeteyRev** [comment]
@bookernath @abrambailey Also having the same issue, this is after updating client to a newer version of cornerstone (v1.10) I checked the older version and its working fine

**Comment by bookernath** [comment]
@PeteyRev do you see the issue when using the AMP CDN, or just when viewing the storefront directly?

**Comment by PeteyRev** [comment]
@bookernath Thanks for the reply. I was initially just doing https://www.MySite.com/amp/product/ It was working find on a developement store we had, but when we pushed is when we started seeing the issue. Are you saying this would not be the correct way to view a BigCommerce Amp site?

**Comment by bookernath** [comment]
Yes, in its current state BC's AMP feature is intended to get AMP pages picked up by the AMP cache. Google will crawl the website, become aware of an AMP version, and then cache it in their CDN.

When loaded from this CDN, the same-origin iframe issue is not a problem.

Long term, we'll want to eliminate this issue by eliminating the iframe and using more native AMP features as they become available. At the moment, it's impossible to support 100% of our Product Options functionality that way, so we have the iframe for compatibility.

You can see the appropriate formatting for the AMP URL which you can use for testing above in my previous reply. :)

**Comment by PeteyRev** [comment]
@bookernath thanks! I am a little confused by the structure of this url though, where would i put my stores url?

**Comment by bookernath** [comment]
@PeteyRev In your example (https://www.mysite.com/amp/product/) you would do:

https://cdn.ampproject.org/c/s/www.mysite.com/amp/product/

If it was HTTP and not HTTPS, you would do:

https://cdn.ampproject.org/c/www.mysite.com/amp/product/

**Comment by PeteyRev** [comment]
@bookernath Thanks!

**Comment by shotaK** [comment]
@bookernath we are trying to add AMP to our store, which is based on Cornerstone 2.0 version. I think we are facing the same issue as this, but errors are different (I saw amp-iframe error too). AMP validation is successful.

![screen shot 2018-06-14 at 7 00 29 pm](https://user-images.githubusercontent.com/3370367/41420449-7a37c2a4-7005-11e8-99dd-c816c698e03e.png)

We don't want to activate AMP on production site as we are using a custom theme and AMP might break things. So we are trying to test AMP on Bigcommerce sandbox, which we don't want to be crawled by Google.

So the question is, is there any way to test AMP pages on the sandbox without Google crawling it? if there is not, what would be our best bet?

**Comment by junedkazi** [comment]
Going to close this issue since this is a restriction due to amp-iframe limitations https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md. Also we have a workaround in the comments above.
