### ISSUE TITLE
Changing product options does not update displayed price, image, etc.

### ISSUE THREAD

**Issue by siliconforks** [bigcommerce/cornerstone#1109]
### Expected behavior

On a product page, changing product options should cause the displayed price, image, etc. to change.

### Actual behavior

The displayed price, image, etc., never change when an option is changed.

### Steps to reproduce behavior

1. Create a product with a multiple-choice option, displayed in a dropdown
2. Create a rule which changes the price, image, etc. when a certain option value is selected
3. Visit the product page and select the option value in the dropdown.  This used to cause the displayed price, image, etc. to change, but this no longer works.

I'm using Cornerstone 1.9.4 with Stencil-utils 1.0.8.  This appears to be caused by a bug in Stencil-utils 1.0.8 - downgrading to Stencil-utils 1.0.7 fixes the issue.  (But the stencil-utils repo doesn't seem to provide a way to submit issues?  So I'm reporting it here.)

**Comment by steve-ross** [comment]
Having the same problem here and it has been driving me nuts. Thought we were going crazy.

**Comment by steve-ross** [comment]
Opened a PR to fix it

**Comment by sacr3dc0w** [comment]
@steve-ross Your fix doesn't seem to solve the problem either. I'm still not able to update price, SKU, or swap out images.

**Comment by creativesafetysupply** [comment]
#1118 fixed this! 👍

**Comment by junedkazi** [comment]
If this is still an issue please reopen.
