### ISSUE TITLE
It's hard to track submission of the contact form

### ISSUE THREAD

**Issue by Tiggerito** [bigcommerce/cornerstone#1114]
### Expected behavior
When someone submits the contact form it should be possible to track that submission in systems like Google Analytics. Even better if we can track the funnel flow of a submission attempt to analyse what issues people have.

### Actual behavior
The contact form is a single page powered by JavaScript. There is no simple way to detect if the form has been submitted.

### Steps to reproduce behavior
Submit a contact form.

### Possible solution 1
Provide some ways to hook into events that happen while submitting a form. e.g. submission errors, captcha failures and then final success. 

### Possible solution 2
I've developed some JavaScript to detect changes in the page and trigger Google Analytics events on submissions and displaying errors. 

To make it work I need to edit some of the theme files by adding ids to some elements. It would be a lot nicer if I did not need to edit the themes. My notes:

The contact-us-page and contact-us-success ids need adding to templates/pages/contact-us.html. e.g.

<div **id="contact-us-page"** class="page-content page-content--centered">
    {{#if forms.contact.success}}
            <div **id="contact-us-success"**>{{{lang 'forms.contact_us.successful' shopPath=urls.home}}}</div>
    {{ else}}
    <p>{{{page.content}}}</p>
    {{> components / page / contact - us - form}}
        {{/if}}
</div>

contact-us-error needs adding to templates/components/contact-us-form.html. Dynamic validation avoids this, but the captcha triggers it

{{ #if forms.contact.error}}
<div **id="contact-us-error"**>{{> components / common / alert - error forms.contact.error}}</div>
{{/if}}

**Comment by Ubersmake** [comment]
Thank you, @Tiggerito ! We've merged #1317.
