### ISSUE TITLE
Fixing Carousel Next Prev Buttons

### ISSUE THREAD

**Issue by thetechie92** [bigcommerce/cornerstone#1121]
For desktop and mobile the next and prev buttons are not centered. In /assets/scss/components/vendor/slick/_slick.scss if you remove margin-top: -(remCalc(30px)); at line 25 and in /assets/scss/components/stencil/heroCarousel/_heroCarousel.scss just make .slick-next, .slick-prev "top: 50%;" for both views it will fix that issue for ocd people like me.

**Comment by mjschock** [comment]
@thetechie92 thanks for the PR!  closing with https://github.com/bigcommerce/cornerstone/pull/1112
