### ISSUE TITLE
Where do the "snippets" contents come from?

### ISSUE THREAD

**Issue by jbruni** [bigcommerce/cornerstone#1129]
I'm working in a customized Stencil theme, based on Cornerstone.

Throughout the liquid code, I can see these (sorted alphabetically here):

```
{{{snippet 'account'}}}
{{{snippet 'brand'}}}
{{{snippet 'cart'}}}
{{{snippet 'categories'}}}
{{{snippet 'footer'}}}
{{{snippet 'forms_search'}}}
{{{snippet 'header'}}}
{{{snippet 'home_content'}}}
{{{snippet 'htmlhead'}}}
{{{snippet 'product_addtocart'}}}
{{{snippet 'product_rating'}}}
{{{snippet 'reviews'}}}
```

At Stencil documentation, there is no documentation about `snippets` at Handlebars section.

I could not find reference about these "snippets" anywhere. Is there any documentation about them?

Where do these "snippets" contents come from?

**Comment by divyadoshi** [comment]
Hello, 

I am also trying to find snippet folder, but unable to find.
I am using Cornerstone theme,
Please help me out of this.

Thanks!

Regards,
Divya

**Comment by flyingL123** [comment]
I believe that snippets are code that can be 'injected' into the theme from the control panel. I remember reading about these at some point in the early documentation for Stencil, but I don't know where they stand now. I don't see any reference to them in the current documentation.

Maybe it's some sort of in-progress feature still being built.

**Comment by scottcwilson** [comment]
The BigCommerce snippets appear to be closed-source and not modifiable.

**Comment by flair-duncan** [comment]
They're not code snippets - which is why you can't find any theme files to modify - just regions to inject additional front end content, but appear to be a legacy feature.

See #1193 for additional insight and future plans.

**Comment by junedkazi** [comment]
@jbruni https://github.com/bigcommerce/cornerstone/pull/1193 PR should address your question. If you have any further question please reopen this issue.

**Comment by dchavours** [comment]
If there just regions to inject, then why aren't we just replacing it with the {{ inject }} operator?

**Comment by davidangel** [comment]
![Image of Poo Party](https://media.giphy.com/media/1sfPDfTi0Asfe/giphy.gif)
