### ISSUE TITLE
Order History doesn't look right in Firefox

### ISSUE THREAD

**Issue by seth-drf** [bigcommerce/cornerstone#1133]
### Expected behavior
Open firefox, go to `/account.php?action=order_status` and login. You should see your orders with an image next to each order's details.

### Actual behavior
The details for each order overlaps each order's image.

### Steps to reproduce behavior
Make sure the installed theme is Cornerstone Light Version 1.10.0. I haven't checked other versions or other styles.

I think this may have been caused by the changes from https://github.com/bigcommerce/cornerstone/pull/1104

**Comment by bookernath** [comment]
FYI @BC-EChristensen

**Comment by junedkazi** [comment]
I believe this should be fixed by this PR https://github.com/bigcommerce/cornerstone/pull/1137

**Comment by mjschock** [comment]
closing as it appears to have been fixed with #1137 
@seth-drf please re-open if you're still seeing the issue
