### ISSUE TITLE
Linking to IDs in tabbed sections do not open those tabs

### ISSUE THREAD

**Issue by jkelly-cas** [bigcommerce/cornerstone#1136]
### Expected behavior
Visiting http://cornerstone-light-demo.mybigcommerce.com/all/orbit-terrarium-large/#tab-similar should open the #tab-similar section automatically. 

### Actual behavior
Site scrolls to the reviews section, but does not open the tab.

### Steps to reproduce behavior
Visit http://cornerstone-light-demo.mybigcommerce.com/all/orbit-terrarium-large/#tab-similar
page will not open #tab-similar section

See http://arcade-natural-demo.mybigcommerce.com/trekking-axe-classic/#product-tab-information for a working demo.

See http://partswarehouse-classic-demo.mybigcommerce.com/heater-bypass-hose-tube/#tab-similarProducts for another non-working demo.

### Notes
This would be really handy for bookmarking purposes and linking from other pages to specific sections in tabs.

**Comment by funvill** [comment]
Any update on this issue ? I am also experiencing it

**Comment by funvill** [comment]
Re-posted to bigcommerce forms 
https://forum.bigcommerce.com/s/question/0D51B00004IKmeBSAT/

**Comment by junedkazi** [comment]
@funvill @jkelly-cas can you give us any additional information like OS, browser on which it is happening. I am currently on Chrome 65.0.3325.181 on a Mac OS High Sierra. See the video below https://www.useloom.com/share/ce09629a6965449e9a9c43a99a30f59d

**Comment by flyingL123** [comment]
@junedkazi you're video shows the bug. The link goes to `#tab-similar`, but it isn't open. The open tab is the default `#tab-related`.

**Comment by funvill** [comment]
Chrome 65 
Windows 10
http://whatsmybrowser.org/b/K64CMXW

Two tabs at the bottom of the screen. 

- Customers Also Viewed (#tab-similar) 
- Related Products (#tab-related) 

When I got to the page with the following url https://cornerstone-light-demo.mybigcommerce.com/all/orbit-terrarium-large/#tab-similar I was expecting to see the "Customers Also Viewed" tab instead of the "Related Products" tab. 

Same problem exists in your video.

**Comment by funvill** [comment]
![click](https://user-images.githubusercontent.com/314120/38333831-8eccf998-380e-11e8-8da5-9d95c2fc7f8a.gif)

**Comment by junedkazi** [comment]
@funvill @flyingL123 thanks for correcting me. I see the issue now.

**Comment by sacr3dc0w** [comment]
@jkelly-cas #1304

**Comment by junedkazi** [comment]
#1304
