### ISSUE TITLE
sass function for text-transform

### ISSUE THREAD

**Issue by bigmadness** [bigcommerce/cornerstone#1139]
Hi I wanna know is there any wanna know is there any sass function for  text-transform?

https://stencil.bigcommerce.com/docs/custom-sass-functions#Color

**Comment by thetechie92** [comment]
I couldn't find anything. What you could do is put in $text-transform: and then whatever you want it to be in one of the setting scss (I did the container) and in the css part do text-transform: $text-transform;. That is the easiest and quickest way to do that.
