### ISSUE TITLE
Product Carousel don't show when click 'Customers Also Viewed' tab

### ISSUE THREAD

**Issue by ElynJin** [bigcommerce/cornerstone#1146]
On product detail page,  when click 'Customers Also Viewed' tab the first time, the Product Carousel under this tab don't show. Only if you rezise the window or change a CSS style for Product Carousel on Developer tool, the Product Carousel will show.

**Comment by bc-zoharmuzafi** [comment]
@ElynJin This issue was fix https://github.com/bigcommerce/cornerstone/pull/1290
