### ISSUE TITLE
Akami image optimizer

### ISSUE THREAD

**Issue by PeteyRev** [bigcommerce/cornerstone#1169]
### Expected behavior
images that use the default zoom library pass through Akami Image Manager

### Actual behavior
the product page main image has the `imbypass=on` atrribute - will these eventually be optimized or do I need to change something in the src code? Does not look like I can change in the template files

### Steps to reproduce behavior
Open product page and inspect element on main product image

**Comment by junedkazi** [comment]
@PeteyRev currently we do not pass the zoom images through the akamai image manager. The reason being when we did our initial testing with beta merchants we noticed that if we pass the zoom images through the image manager the images details looked a bit blurred (not of high quality) when using the zoom feature. 

If you think the images will look good on your store if they are passed through the image manager just use some sting manipulation & remove  `imbypass=on` from the image urls.

**Comment by PeteyRev** [comment]
@junedkazi Thanks! I think this will work for me quality wise, if anyone else is interested I just used the `{{stripQuerystring}}` helper on the main images

**Comment by flyingL123** [comment]
@PeteyRev @junedkazi - is it safe to completely remove the query string? Couldn't BigCommerce end up adding some additional data to the query string in the future? If they do, you'll lose it. Maybe for caching or something like that.

I think it might be better to use the `replace` helper, unless there is a better one for inline string search and replace.

Shouldn't something like this work?

```
{{#replace "imbypass=on" image_url}}{{/replace}}
```

**Comment by PeteyRev** [comment]
@flyingL123  excellent point, thanks for pointing that out. the syntax looks verbose on the product pages, but it works!
`<img class="productView-image--default" itemprop="image" src="{{#replace 'imbypass=on' (getImage product.main_image 'product_size'  (cdn theme_settings.default_image_product))}}{{/replace}}"`
