### ISSUE TITLE
Quantity Change on Cart page causes shipping estimate to freeze

### ISSUE THREAD

**Issue by aldemeery** [bigcommerce/cornerstone#1194]
### Expected behavior
When you change the quantity in the cart you should be able to get the shipping quotes and 'Additional Rates' link to work without having to refresh the page.

### Actual behavior
When you change the quantity in the cart you need to do a refresh in order to get the quotes to load again otherwise the "show additional rates" does not allow you to click it.

### Steps to reproduce behavior
After inspecting the elements, the problem seems to be coming from a div with the class `.estimator-form--ups`
when the `Show additional rates` link is clicked that div is selected and then a class `u-hiddenVisually` is toggled

here is the code for this:

![image](https://user-images.githubusercontent.com/25695783/37909178-8516666a-310a-11e8-8ac2-f153304bff4c.png)

Now for some reason when the number of items in the cart is changed...an extra div with the same class `.estimator-form--ups` is added to the DOM. This is done with every single change in the items number
so if you increment the number of an item in the cart three times you will end up with four divs with the class `.estimator-form--ups`, which causes the link not to work, because you need only one div with that class.

Here's a video of the issue

![video](https://user-images.githubusercontent.com/25695783/37909788-22b44c7e-310c-11e8-8d7b-47729becb9c7.gif)

### Note
we replaced the 'Additional Rates' link with a radio button, but everything is still exactly the same.

**Comment by junedkazi** [comment]
@aldemeery thanks for reporting the issue. We are looking into it & should have an update soon.

**Comment by aldemeery** [comment]
Bump @junedkazi??

**Comment by davidwrpayne** [comment]
@aldemeery  This should is no longer an issue as the ups rates are now shown flattened.
