### ISSUE TITLE
Too many open files error in the first run start

### ISSUE THREAD

**Issue by xpothemes** [bigcommerce/cornerstone#1200]
I'm having a problem with "**stencil start**". 
See this below screenshot:
![image](https://user-images.githubusercontent.com/36004695/38678553-888c9ede-3e8b-11e8-8c23-cad397c2acd5.png)

It only appears in the first run. I have to run "**stencil start**" again then it working normally.
However, in the process of editing it continued to appear. And then i have to run **stencil start** again.
It's really very annoying.

Is there a way to fix it?
Thanks!

**Comment by junedkazi** [comment]
@xpothemes this seems like a stencil-cli issue. Can you please move it to that issue queue & close this one.
