### ISSUE TITLE
Fix brands import statement

### ISSUE THREAD

**Issue by nowlena** [bigcommerce/cornerstone#1201]
### Expected behavior
app.js should include `brands` code on the `brands` page class

### Actual behavior
app.js loads `brand` code on the `brands` page class

### Steps to reproduce behavior
See https://github.com/bigcommerce/cornerstone/blob/master/assets/js/app.js#L31
Change this line to:
```javascript
    brands: () => import('./theme/brands'),
```

**Comment by junedkazi** [comment]
I would welcome a PR to fix it.

**Comment by junedkazi** [comment]
Fixed part of https://github.com/bigcommerce/cornerstone/pull/1202
