### ISSUE TITLE
Lazyload product videos - videos.html

### ISSUE THREAD

**Issue by PeteyRev** [bigcommerce/cornerstone#1217]
Any reason why this is not being utilized?

```
            <iframe
                id="player"
                type="text/html"
                width="640"
                height="390"
                frameborder="0"
                webkitAllowFullScreen
                mozallowfullscreen
                allowFullScreen
                class="lazyload"
                data-src="//www.youtube.com/embed/{{this.featured.id}}"
                data-video-player>
            </iframe>

```

Id be happy to make a pull request, just wondering since the video thumbnails are being lazy loaded

**Comment by bookernath** [comment]
PR welcome!

**Comment by PeteyRev** [comment]
@bookernath Thanks, [done](https://github.com/bigcommerce/cornerstone/pull/1218)

I also noticed a bigger issue that is fixed in the same PR, the video thumbnails when clicked aren't changing the main video

**Comment by junedkazi** [comment]
Fixed in https://github.com/bigcommerce/cornerstone/pull/1221
