### ISSUE TITLE
PR #1205 has introduced a display glitch when faceted search is enabled

### ISSUE THREAD

**Issue by flair-duncan** [bigcommerce/cornerstone#1224]
### Expected behavior
- Choosing a filter in the faceted search panel should replace `.page-sidebar` content on the category page.

### Actual behavior
- Choosing a filter appends the content `components/category/sidebar.html` into the existing `.page-sidebar` element, so this becomes 25% width of the parent container
- This was caused by bringing `<aside class="page-sidebar" id="faceted-search-container">` into the sidebar component in PR #1205 

### Steps to reproduce behavior
- Visit the [Cornerstone demo](http://cornerstone-light-demo.mybigcommerce.com/all/) category page and click a filter
- [Video of issue](https://www.useloom.com/share/4de68535ea524866a51e02552f7b7aeb)

### How to resolve
- The quickest fix is to bring `<aside class="page-sidebar" id="faceted-search-container">` back into `pages/category.html`

```
<aside class="page-sidebar" id="faceted-search-container">
    {{> components/category/sidebar}}
</aside>
```

**Comment by junedkazi** [comment]
@tpietsch
