### ISSUE TITLE
Filtering bug on dropdown Safari OSX

### ISSUE THREAD

**Issue by enkota** [bigcommerce/cornerstone#1231]
There seems to be an issue when clicking on the sidebar filter checkbox. After clicking a checkbox, the column will become very narrow. Using Safari on OSX.

![screen shot 2018-05-09 at 10 06 30](https://user-images.githubusercontent.com/13979799/39806092-dd2767f4-5370-11e8-920d-3115708082a1.png)

Testing on the Cornerstone demo site. Not sure if this has been fixed already.

**Comment by flair-duncan** [comment]
Should be fixed: Issue #1224, PR #1225 

The Cornerstone demo site might need a theme update.

**Comment by enkota** [comment]
Ah thanks for that, missed those.
