### ISSUE TITLE
Missing documentation for "stencilImage" custom SASS function

### ISSUE THREAD

**Issue by jbruni** [bigcommerce/cornerstone#1235]
At ["Custom Sass Functions" Stencil documentation page](https://stencil.bigcommerce.com/docs/custom-sass-functions), we have these custom SASS functions properly documented:

- [`stencilColor`](https://stencil.bigcommerce.com/docs/custom-sass-functions#Color)
- [`stencilFontFamily`](https://stencil.bigcommerce.com/docs/custom-sass-functions#FontFamily)
- [`stencilFontWeight`](https://stencil.bigcommerce.com/docs/custom-sass-functions#Weight)
- [`stencilNumber`](https://stencil.bigcommerce.com/docs/custom-sass-functions#Number)
- [`stencilString`](https://stencil.bigcommerce.com/docs/custom-sass-functions#String)

But documentation for `stencilImage` is missing.

I see this custom SASS function being used in Cornerstone 1.18.0 theme, but I wonder what it does.

See [`assets/scss/optimized-checkout.scss`, line 25](https://github.com/bigcommerce/cornerstone/blob/1.18.0/assets/scss/optimized-checkout.scss#L25).

**Comment by karen-white** [comment]
Thanks for catching this @jbruni ! We'll get it updated in our documentation.

The stencilImage function accepts the image URL of an image uploaded to the Theme Editor and the size selected for the image. It returns the string value of the image URL with the size input by the user.

https://github.com/bigcommerce/stencil-styles/blob/ef144901dfc049c3c6ff9a259a6c0473a73f1daa/lib/styles.js#L140

**Comment by junedkazi** [comment]
Thanks for reporting this issue. Documentation has been added here https://developer.bigcommerce.com/stencil-docs/css-and-design-assets/custom-sass-functions#custom-sass-functions_stencilimage

**Comment by wearegoose** [comment]
I was wondering if somebody could provide an example. I have tried to use this, but can't get it working. An example would make it crystal clear. Thanks
