### ISSUE TITLE
Price Restrict to Logged in user

### ISSUE THREAD

**Issue by amandeepsinghvirdi** [bigcommerce/cornerstone#1240]
In Theme option if we check the option "restrict to login" and user is currently logged in, then in quick search they should be able to see the price of the products. 

But currently it is not showing the price (even if user is logged in). 

### Steps to reproduce behavior

1. Check the option "Restrict to Login"
2. Now browse the store, you'll notice that you'll not be able to see the price of the product
3. Now Login to a customer account, and again browse the website (categories, homepage etc). Everything is working fine.
4. Click on "Search" in the header and type any search query which shows the product list, You'll notice that it will not show the price. It will still show the message "Login to see pricing".  

**Fix:**
File Path: 
cornerstone/templates/components/search/quick-results.html

We need to pass customer in the variables to card component. 

`{{> components/products/card alternate=true show_compare=../show_compare theme_settings=../theme_settings customer=../customer}}
`

**Comment by junedkazi** [comment]
Fixed in https://github.com/bigcommerce/cornerstone/pull/1272
