### ISSUE TITLE
Cart Clickable Link doesn't work on mobile

### ISSUE THREAD

**Issue by bigmadness** [bigcommerce/cornerstone#1249]
problem url -  https://forum.bigcommerce.com/s/question/0D51B00004P6KUFSA3/cart-clickable-link-doesnt-work-on-mobile-cornerstone-theme?s1oid=00D30000001FDCG&OpenCommentForEdit=1&s1nid=0DB13000000Gmw5&emkind=chatterCommentNotification&s1uid=0051B00000Cdq7l&emtm=1527421437373&fromEmail=1&s1ext=0 
 
- Cornerstone  100% full width click on logo.

**Comment by junedkazi** [comment]
fixed in https://github.com/bigcommerce/cornerstone/pull/1296
