### ISSUE TITLE
Missing webpack js files in the bundle file of version 2.0.0

### ISSUE THREAD

**Issue by xpothemes** [bigcommerce/cornerstone#1251]
Today, i've updated cornerstone theme to v2.0.0. 
But I see in file bundle file doesn't have the webpack js files (**webpack.common.js**, **webpack.dev.js**,  **webpack.prod.js**)
See this below screenshot: (webpack js files are missing)
![image](https://user-images.githubusercontent.com/36004695/40716012-c65946c4-6431-11e8-8df1-220fe6139315.png)

**Comment by mattolson** [comment]
I have updated Stencil CLI and released it as version 1.15.0

**Comment by xpothemes** [comment]
Awesome! Thanks you :)

**Comment by techxlers** [comment]
That did not solve the issue. So what I did is. I downloaded the source code file and copy following files in my directory "webpack.common.js", "webpack.dev.js", and "webpack.prod.js". That solved the problem.

**Comment by xpothemes** [comment]
@techxlers That was fixed in the latest version of Stencil-Cli. So you need to reinstall Stencil-Cli.

**Comment by techxlers** [comment]
I have updated the Stencil-Cli but it was not working. Also, as far as I understand the issue is files are missing from the directory that's why it was not working :)
