### ISSUE TITLE
currency dropdown arrow

### ISSUE THREAD

**Issue by bigmadness** [bigcommerce/cornerstone#1254]
currency dropdown arrow position need to be on right side.
![40763100-36d4bae6-64c3-11e8-8ef2-c3bc1d844051](https://user-images.githubusercontent.com/10583985/40889623-d6171536-6789-11e8-86bf-08f59f0c1975.png)

**Comment by junedkazi** [comment]
Fixed by https://github.com/bigcommerce/cornerstone/pull/1267
