### ISSUE TITLE
Mini Cart issue

### ISSUE THREAD

**Issue by acstan** [bigcommerce/cornerstone#1264]
Using Cornerstone v2.1.0

There is a issue with the Mini Cart when doing a certain process.
First go to the a product page, Add the product to the cart and click on Continue Shopping after doing that remain on the product page and click the Cart button in the header, the Mini Cart opens on the right side allowing for horizontal scroll.

This happens on any product page if you click the cart button.

I have used Chrome,Firefox,Safari in Development and Production and the issue is consistent.

I have used the default Cornerstone theme with no modifications, just linked to the shop.

![a](https://user-images.githubusercontent.com/17141804/41186277-79042d04-6b9c-11e8-918e-66c06375c871.jpg)
![b](https://user-images.githubusercontent.com/17141804/41186278-7bcb9aae-6b9c-11e8-8bd3-157e4c421f03.png)
![c](https://user-images.githubusercontent.com/17141804/41186279-7e20d2d8-6b9c-11e8-9670-c8a765060f63.jpg)

**Comment by karen-white** [comment]
I'm having some trouble replicating, @acstan . Are there any other details you can share about the screen size you're using, or a video?

**Comment by sacr3dc0w** [comment]
@acstan @karen-white It's not very consistent but I was able to replicate it. PR #1298 submitted for review.

![01 before](https://user-images.githubusercontent.com/5056945/42195589-5cc987c0-7e2e-11e8-906b-1f80d292ccf6.gif)
![02 after](https://user-images.githubusercontent.com/5056945/42195607-87d0dac2-7e2e-11e8-8220-a3d6229474ed.gif)

**Comment by sacr3dc0w** [comment]
@acstan Can you let me know if #1298 fixed the issue for you? IIRC, it was included with 2.3.0.

**Comment by davidwrpayne** [comment]
Fixed by https://github.com/bigcommerce/cornerstone/pull/1298.
