### ISSUE TITLE
jQuery is not defined ($ as well)

### ISSUE THREAD

**Issue by waheed1987** [bigcommerce/cornerstone#1269]
Hi,
I have added custom javaScript file in the content directory and was able to include it in the footer.
But when I tried to use any jQuery code (with jQuery or $ notation) it gets failed, with the message of "jQuery is not defined".

I can't see jQuery file included in the source as well. What am I doing wrong here?

**Comment by waheed1987** [comment]
My file is the last thing in the page source. http://prntscr.com/jung5n

**Comment by karen-white** [comment]
@waheed1987 In Cornerstone, jQuery isn't globally available; it's scoped locally to the JS files that import it. You can use jQuery within the theme's JS files, but if that's not an option, you will need to include jQuery again.

**Comment by junedkazi** [comment]
@waheed1987 I am closing this ticket. Please reopen if @karen-white solution does not work for you.
