### ISSUE TITLE
mobile banner text underline

### ISSUE THREAD

**Issue by bigmadness** [bigcommerce/cornerstone#1303]
![screen shot 2018-07-07 at 11 45 32](https://user-images.githubusercontent.com/10583985/42407401-99dc46ce-81db-11e8-99e7-fdd6e48a061b.png)

**Comment by oggede** [comment]
Yes, I find this underlining really annoying. Especially when with lower case letters that hang down, for example the word "Light". Look at the letter "g", it is overlapping and looks really bad.

I think underlining should be removed by default.

**Comment by bookernath** [comment]
PRs are welcome on this one in case we don't get to it in the near term!

**Comment by junedkazi** [comment]
See #1482
