### ISSUE TITLE
Customer Order grid link issue.

### ISSUE THREAD

**Issue by ghost** [bigcommerce/cornerstone#1330]
### Expected behavior
**Customer My Account Page**

- Order listing page showing order. when user go to order details **order** link will be order listing page.

### Actual behavior
- Now when user goto order listing page to order details. On order details **Order** tab is no link to go to order listing page.

### Steps to reproduce the behavior

- Place ann order
- Goto order listing page.
- Goto order detail pahe.
- No link to goto order listing page.

### Solution
**Current Code**

`{{#if account_page '===' 'orders'}}<li class="navBar-item is-active">{{lang 'account.nav.orders'}}</li>{{else}}<li class="navBar-item"><a class="navBar-action" href="{{urls.account.orders.all}}">{{lang 'account.nav.orders'}}</a></li>{{/if}}`

**Solution Code**
`{{#if account_page '===' 'orders'}}
    {{#if page_type '===' 'account_order'}}
        <li class="navBar-item is-active">
            <a class="navBar-action" href="{{urls.account.orders.all}}">{{lang 'account.nav.orders'}}</a>
        </li>
    {{else}}
        <li class="navBar-item is-active">{{lang 'account.nav.orders'}}</li>
    {{/if}}
{{else}}
    <li class="navBar-item">
        <a class="navBar-action" href="{{urls.account.orders.all}}">{{lang 'account.nav.orders'}}</a>
    </li>
{{/if}}`

**Comment by sacr3dc0w** [comment]
Watching football and coding so I made a PR. #1343 Thanks for the solutions. Cheers!

**Comment by Ubersmake** [comment]
Hi @hiteshvaghasiya83 . It looks like this was addressed in #1343, which was released as a part of Cornerstone 2.4.0: https://github.com/bigcommerce/cornerstone/releases/tag/2.4.0 . If this has addressed this issue, could you close it?
