### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by napalm272** [bigcommerce/cornerstone#1331]
### Expected behavior
https://stencil.bigcommerce.com/docs/customizing-javascript should be up to date

### Actual behavior
In cornerstone 2.3.2-rc.1, `/assets/js/theme/product.js` looks very different than what's on the page above.  This is the commit that caused the inconsistency: https://github.com/bigcommerce/cornerstone/commit/31bdddbf64293d85192cae00e966d531f527b150#diff-eaddb008b4dd357a417047430ec8ea40

### Steps to reproduce behavior
Follow the stencil quick start guide.

**Comment by napalm272** [comment]
https://stencil.bigcommerce.com/docs/js-pg-cycle references these methods: `before`,`loaded` and `after`.  Are they merged to `onReady`?  Were the separate lifecycle events not useful?

**Comment by nikita-ahuja** [comment]
Hi @napalm272! 

This is a great callout! I work on the developer documentation at BigCommerce, and we're in the process of updating the documentation to reflect the changes that occurred once Cornerstone was updated to Webpack 4. We'll be sure to get this updated.

Thanks again!

**Comment by Plonq** [comment]
Don't forget the README :)

**Comment by sacr3dc0w** [comment]
The documentation for this section ([adding-javascript#adding_mapping-custom](https://developer.bigcommerce.com/stencil-docs/custom-javascript-implementations/adding-javascript#adding_mapping-custom)) needs updated at some point to reflect #1339.

**Comment by dsmarion** [comment]
still not updated in readme in version 2.6.0

**Comment by junedkazi** [comment]
Documentation is updated to reflect changes and issue is resolved with PR #1419
