### ISSUE TITLE
Customizing Invoices

### ISSUE THREAD

**Issue by PeteyRev** [bigcommerce/cornerstone#1332]
I had been referring to [this](https://stencil.bigcommerce.com/docs/customizing-printable-invoices) documentation for editing invoices. But with the last release update I noticed there is an actual invoice template you can edit? there is also an order object too. Is this new? How do I test this locally?

**Comment by nikita-ahuja** [comment]
Hi @PeteyRev!

The document you’re referring to provides steps to customize the printable invoice that can be printed from the control panel.

The [invoice.html](https://github.com/bigcommerce/cornerstone/blob/master/templates/pages/account/orders/invoice.html) file, however, renders the printable invoice that can be printed by a shopper who has a store account. When a shopper with an account navigates to the specific order page, there is a ‘print invoice’ button on the order’s page that will allow a shopper the shopper to print an invoice. You can modify invoice.html to customize this. You can test locally using the [Stencil CLI](https://stencil.bigcommerce.com/docs/installing-stencil-cli-1).

**Comment by PeteyRev** [comment]
@nikita-ahuja got it, thanks!
