### ISSUE TITLE
Add new screen size handler bar in cornerstone.

### ISSUE THREAD

**Issue by taruntds** [bigcommerce/cornerstone#1333]
Few days ago, i have researched and found that we can create custom handle bars but we cannot implement the same in cornerstone neither customising the code. So, can anyone please help or let me know how can i add the new handle bar in cornerstone. 

Regarding screen size handlebar, this will calculate the window width same like CSS. Having this handlebar will also help developers to duplicate the structure in their code where needed. 

**For example:**
If anyone wants to add mobile specific carousel image and only want to show that image in mobile device then developer can use this "Screen Size" handle bar and can show the carousel images in mobile only, same applies for other structures too.

It will also increase page speed of store by not showing the duplicate content or structure in desktop.

**Comment by taruntds** [comment]
@karen-white 

Could you please look at this new feature which i am requesting.

**Comment by taruntds** [comment]
Can anyone give me a update on this. @karen-white @junedkazi

**Comment by junedkazi** [comment]
@taruntds For security reasons, BigCommerce does not allow Stencil developers to define new custom Handlebars helpers – you must use the helpers currently available. However, you can suggest new custom helpers via a pull request to the [paper-handlebars](https://github.com/bigcommerce/paper-handlebars) Github repo.

**Comment by taruntds** [comment]
Hello @junedkazi 

Can you please give a little more guide on how to submit that handler in paper-handlebars. Is paper-handlebars are using in cornerstone bigcommmerce?

**Comment by junedkazi** [comment]
@taruntds I stand corrected. You will have to do the following;

- Add the handlebar helper [here](https://github.com/bigcommerce/paper/tree/2.x/helpers)(**NOTE:** Make you you are in the 2.x branch & not master).  
- We are trying to split all the helpers into its own repo [paper-handlebars](https://github.com/bigcommerce/paper-handlebars) but it not yet in production. In paper-handlebars you can add your helper [here](https://github.com/bigcommerce/paper-handlebars/tree/master/helpers). 
- Just look at existing handlebar implementations & it should be a good guide. 
- You can use stencil cli to test your changes by pointing the to your forked version/branch/pr of paper https://github.com/bigcommerce/stencil-cli/blob/master/package.json#L38 (From step 1)

paper handlebars are used in stencil-cli to support local development & it is also used in the app which powers all the stores rendering.

**Comment by Ubersmake** [comment]
Hi @taruntds . Have you had any success with the suggestions in the comment prior, https://github.com/bigcommerce/cornerstone/issues/1333#issuecomment-416684850. Is this still a feature request you'd like to see?

**Comment by taruntds** [comment]
Hello @Ubersmake,

I have already tested with script but i haven't pushed in helper folder. Can you please let me know whether can i push "Screen Size" script directly in "Paper Handler" instead of "Paper Repo"

**Comment by junedkazi** [comment]
@taruntds if you think it could benefit the BigCommerce theme developer community please open a PR based on the steps listed above and someone from the team can review it.
