### ISSUE TITLE
Cart Page - Cancel button on mobile should have a left space.

### ISSUE THREAD

**Issue by shotaK** [bigcommerce/cornerstone#1352]
### Expected behavior
Cancel button on mobile should have a left space.

### Actual behavior
Cancel button on mobile does not have left space

### Steps to reproduce the behavior
1. Add any product to the cart.
2. Go to the cart page.
3. Click removing the product from the cart with X button

### Image
![screen shot 2018-09-21 at 1 13 18 pm](https://user-images.githubusercontent.com/3370367/45872433-17b62f00-bda1-11e8-957e-dbd975f63e3e.png)

**Comment by sacr3dc0w** [comment]
#1363 fixes this

**Comment by Ubersmake** [comment]
Hi @shotaK. This has been addressed in #1363, which was in Cornerstone 2.5.1: https://github.com/bigcommerce/cornerstone/releases/tag/2.5.1 . If this is no longer an issue, could you close this issue?

**Comment by Ubersmake** [comment]
Hi @shotaK . I'm going to close this issue because of the fix in #1363 . Please reopen if it appears in the future.
