### ISSUE TITLE
Product filters do not keep the previously selected color filter when the price filter is the top.

### ISSUE THREAD

**Issue by anilgautamm** [bigcommerce/cornerstone#1367]
### Expected behavior
Product filters should preserve filters after range selection when price filter is the top.

### Actual behavior
Product filters do not keep the previously selected color filter when the price filter is the top.

### Steps to reproduce the behavior
when the price filter is the top.
https://www.useloom.com/share/f3bcb360539243beb01b6488d21f9e08

**Comment by Ubersmake** [comment]
First mentioned in https://github.com/bigcommerce/cornerstone/pull/1232#issuecomment-426264136.

**Comment by HikeOn** [comment]
Hi,

The issue got resolved for us after we replaced the code 
  
   **onRangeSubmit(event) {
        event.preventDefault();
        if (!this.priceRangeValidator.areAll(nod.constants.VALID)) {
            return;
        }
        const url = Url.parse(window.location.href);
        const queryParams = decodeURI($(event.currentTarget).serialize());
        urlUtils.goToUrl(Url.format({ pathname: url.pathname, search: `?${queryParams}` }));
    }**


in **faceted-search.js** file with

 **onRangeSubmit(event) {
         event.preventDefault();
          if (!this.priceRangeValidator.areAll(nod.constants.VALID)) {
            return;
          }
        const url = Url.parse(window.location.href);        
        const avoidSearchQuery = 'search_query=';
        const urlParams = new URLSearchParams(window.location.search);
        const avoidSortValue = 'sort='+ urlParams.get('sort');
        let queryParams = decodeURI($(event.currentTarget).serialize());
        let path = url.path;
        let urlValue;
        if(path.indexOf('?') !== -1){
            path = path.replace(avoidSortValue,'');
            queryParams = queryParams.replace(avoidSortValue,'');
            if(path.indexOf(avoidSearchQuery) !== -1){
                if(path.indexOf(avoidSearchQuery+'&m') !== -1){
                   path = path.replace(avoidSearchQuery+'&min_price='+urlParams.get('min_price')+'&max_price='+urlParams.get('max_price'),'');                  
                }else{
                    path = path.replace(avoidSearchQuery,'');                  
                }
            }
            urlValue = path + `&${queryParams}`;
            urlValue = urlValue.replace(/&&*\[\]=*/g,'').replace(/&&*/g,'&').replace(/\?&/g,'\?');
            if(urlParams.get('sort') !== null){
                urlValue = urlValue + '&' + avoidSortValue;
            }
        }else{
            urlValue = Url.format({ pathname: url.pathname, search: `?${queryParams}` });
        }
        urlUtils.goToUrl(urlValue);
    }**

**Comment by Ubersmake** [comment]
This has been fixed in [3.4.1](https://github.com/bigcommerce/cornerstone/releases/tag/3.4.1) as a part of #1471. This should be published to all stores within the next two weeks.
