### ISSUE TITLE
Schema Payment Buttons doesn't work

### ISSUE THREAD

**Issue by anvucodespot** [bigcommerce/cornerstone#1386]
I see you had add the new key 

> "enable": "smartButtons"

 to this section, you can find it in line https://github.com/bigcommerce/cornerstone/blob/e2cbbe4a090e27971492cfe4a7d621669db1f0dd/schema.json#L2629 . Unfortunately, it's the reason the theme customizing (customizer) doesn't show "Payment Buttons" section.

### Steps to reproduce behavior
Go to Manager panel > Storefront > My Themes > Customize > Check "Payment Buttons" section.

**Comment by lord2800** [comment]
Do you have Braintree powered by PayPal set up as a payment provider on your store? That's the only time it shows up for now.
