### ISSUE TITLE
`cart.items` returned empty array `[]` but now returns blank

### ISSUE THREAD

**Issue by jbruni** [bigcommerce/cornerstone#1404]
### Expected behavior

In fact, **previous** behaviour.

Until this Monday (Dec 10, 2018), `{{{json cart.items}}}` returned `[]` (JSON notation for an empty array) when the cart was empty.

This is the expected behavior.

### Actual behavior

Since yesterday, `{{{json cart.items}}}` returns a zero-length string, when the cart is empty.

This has broken several sites we develop, because they use a simple code snippet similar to this:

```js
var cartItems = {{{json cart.items}}};
```

When it returned `[]`, there was no error, because this became:

```js
var cartItems = [];
```

Now, returning empty string, the snippet becomes:

```js
var cartItems = ;
```

Which is a syntax error, breaking the code execution.

### Steps to reproduce behavior

- Use the Handlebars code snippet shared above.
- Travel back in time, two days ago, before BigCommerce breaking change has been applied. Confirm the code works as expected.
- Return to present time, and confirm the current backwards incompatible behavior.

We wonder if https://github.com/bigcommerce/cornerstone/pull/1401 is an attempt to bring the already done breaking back-end change to the front-end...

Yep... we have several broken live production stores right now, due to this BigCommerce change.

**Comment by carsonreinke** [comment]
Or related to #1402.  I have case #03586811 in for this too.

**Comment by flair-duncan** [comment]
@jbruni @carsonreinke We're also experiencing some issues with our themes because of this change, we used #1379 as a reference to fix our problems. May or may not be helpful in your case...

**Comment by jbruni** [comment]
@flair-duncan @carsonreinke - Just opened #1405, which is also related.

**Comment by bookernath** [comment]
Thanks @jbruni @carsonreinke @flair-duncan . The team is taking a look today.

**Comment by bookernath** [comment]
This fix is deploying to our first deployment tier in production now. Our support team is able to upgrade any stores still affected. Assuming everything goes well in our rollout, all stores should get the fix within 24 hours. I'll post an update if that changes.

**Comment by jbruni** [comment]
I'm closing the issue because BigCommerce fix deployment has reverted the problem in our stores. All is working fine again, just as before.

Thank you!
