### ISSUE TITLE
`cart.quantity` returned zero`0` but now returns blank

### ISSUE THREAD

**Issue by jbruni** [bigcommerce/cornerstone#1405]
### Expected behavior

In fact, **previous** behaviour.

Until this Monday (Dec 10, 2018), `{{cart.quantity}}` output was `0` (number zero) when the cart was empty.

This is the expected behavior.

### Actual behavior

Since yesterday, `{{cart.quantity}}` returns a zero-length string, when the cart is empty.

This has affected several sites we develop. For example, https://macofalltrades.com

This is how the cart preview link looked like until yesterday:

![before](https://user-images.githubusercontent.com/69181/49880157-b0919f00-fe12-11e8-9a65-3f31014271af.png)

Now, returning empty string, here is how it is looking like:

![after](https://user-images.githubusercontent.com/69181/49880171-b7b8ad00-fe12-11e8-9661-3cc1eb2b8993.png)

### Steps to reproduce behavior

- Use the Handlebars code snippet shared above.
- Travel back in time, two days ago, before BigCommerce breaking change has been applied. Confirm the code works as expected.
- Return to present time, and confirm the current backwards incompatible behavior.

### Related

- **https://github.com/bigcommerce/cornerstone/issues/1404**
- possibly https://github.com/bigcommerce/cornerstone/pull/1379
- possibly https://github.com/bigcommerce/cornerstone/pull/1402
- possibly https://github.com/bigcommerce/cornerstone/pull/1401

### Request

Please revert this breaking change. Or fix it to be backwards compatible. Thank you! :pray:

**Comment by bookernath** [comment]
Thanks; we're looking at this with priority this morning.

As an FYI, https://github.com/bigcommerce/cornerstone/pull/1379 / https://github.com/bigcommerce/cornerstone/pull/1401 / https://github.com/bigcommerce/cornerstone/pull/1402 are not related to the regression; however, we are changing our "best practice" for how to interact with the cart to use FE API calls. You can probably fix this issue for yourself in advance of us deploying backend code to fix it by using the method in https://github.com/bigcommerce/cornerstone/pull/1379 - which will go out with Cornerstone 2.7.0.

We still intend to support the old way of doing things (accessing Cart in handlebars) so we're going to get this fixed as soon as possible.

**Comment by carsonreinke** [comment]
@bookernath While I understand that BigCommerce wants to change this for accessing the cart, it changes how we do things quite dramatically and it is not the best approach.  Cart line items do not have a single use case like presented in that PR.

**Comment by bookernath** [comment]
@carsonreinke can you give an example of what you mean?

Just to make sure I'm articulating this clearly, we don't plan to do anything with the existing {{cart}} resource - we intend to keep supporting it and all the existing themes and stores that might be using it.

However, towards the goal of making the storefront faster, we plan to move the [interactions to the frontend](https://github.com/bigcommerce/cornerstone/pull/1379) and [disable the cart object by default in Cornerstone](https://github.com/bigcommerce/cornerstone/pull/1401) which will result in a faster response time for the page, especially for stores with certain configurations like a lot of discount rules, or shoppers who have a lot of items in their cart.

Anyone who still wants to use the Cart resource can keep it enabled.

All of the same information - such as the cart line items - can be accessed via our [Storefront Cart API](https://developer.bigcommerce.com/api-docs/cart-and-checkout/cart-and-checkout-overview#cart-checkout_storefront-cart-and-checkout), and we've provided a [convenience function for that in stencil-utils](https://github.com/bigcommerce/stencil-utils/blob/master/src/api/cart.js#L11) for accessing it.

**Comment by bookernath** [comment]
@flair-duncan we plan to get a fix out to our first deployment tier today. Our support team will be equipped to fix any stores they're contacted about. We'll consider a more aggressive deployment across all stores later in the day.

**Comment by carsonreinke** [comment]
@bookernath I am going to respond on your PR, so not to mix in.

> Our support team will be equipped to fix any stores they're contacted about

So we have to contact for a specific store?

**Comment by bookernath** [comment]
If you want to guarantee it gets fixed as quickly as possible, I'd advise getting a ticket in with our support team. You can mention our internal JIRA issue: STRF-5787 and ask that your store get upgraded to the fixed version.

If you don't get in touch, you'll still get the fix, just possibly later today. We don't have a means of detecting which stores are affected (functionally) by this issue, so we can only accelerate those we know about.

**Comment by bookernath** [comment]
This fix is deploying to our first deployment tier in production now. Our support team is able to upgrade any stores still affected. Assuming everything goes well in our rollout, all stores should get the fix within 24 hours. I'll post an update if that changes.

**Comment by jbruni** [comment]
I'm closing the issue because BigCommerce fix deployment has reverted the problem in our stores. All is working fine again, just as before.

Thank you!
