### ISSUE TITLE
Video thumbnail bug

### ISSUE THREAD

**Issue by ghostinstallations** [bigcommerce/cornerstone#1411]
v2.6.0. Clicking on the video thumbnails brings you to the top of the product page rather than playing the video in the main video player. I believe this was a resolved bug in the past (id 1218). Can anyone else confirm this is an issue?

**Comment by karen-white** [comment]
Hey @ghostinstallations , I'm having some trouble replicating the issue you're describing on 2.6.0. Mind going through the detailed steps to reproduce or sharing a screencast?

**Comment by ghostinstallations** [comment]
Screencast shown here: https://www.youtube.com/watch?time_continue=2&v=iFHs74QXEc8

**Comment by karen-white** [comment]
Thanks for the update, @ghostinstallations ! Closing this out and we can continue the investigation through support.
