### ISSUE TITLE
No message displayed if no products found

### ISSUE THREAD

**Issue by shotaK** [bigcommerce/cornerstone#1421]
### Expected behavior
When filtering products based on price, if there were no results found it should show the appropriate message to the users.

### Actual behavior
No message is displayed to the users.
![screen shot 2019-01-14 at 2 49 01 pm](https://user-images.githubusercontent.com/3370367/51108513-e8be4000-180b-11e9-8057-7addaf17d424.png)

### Steps to reproduce behavior
1) Go to https://cornerstone-light-demo.mybigcommerce.com/shop-all/garden
2) Enter very big numbers in price filter so that no results will be shown.

**Comment by megdesko** [comment]
@shotaK Thank you for reporting this.  We're working on prioritizing and fixing this.
