### ISSUE TITLE
Is there a way to load external html by url?

### ISSUE THREAD

**Issue by mrself** [bigcommerce/cornerstone#1430]
I remember that some time ago I observed cornerstone docs here https://developer.bigcommerce.com/ and found intereseting feature of handlebars. It allowed to load html by external url. It was handlebars extension. Something like `{{loadUrl http://mysite.com }}`. But now I can not find this feature. Am I mistaken about this feature existing or it was removed for some reason?

It it does not exists, can you suggest the way to implement similar logic on server side not using js?

**Comment by carsonreinke** [comment]
FYI @mrself, helpers are found here: https://github.com/bigcommerce/paper-handlebars/tree/master/helpers

**Comment by mrself** [comment]
@carsonreinke Thanks, it is good to know such reference. But is there a way to add custom helpers?

**Comment by carsonreinke** [comment]
@mrself Sorry, you cannot :frowning_face:

**Comment by mrself** [comment]
Is there any reason for that? Or it is just not implemented?

**Comment by karen-white** [comment]
Hey @mrself , I'd add to Carson's comment and say that we do accept PRs for the Handlebars helper repo that he linked if you'd like to add a custom helper to Stencil. You can either submit a PR to https://github.com/bigcommerce/paper-handlebars/tree/master/helpers directly, OR if you think your helper would benefit the wider Handlebars community, you can submit your helper to [this repo](https://github.com/helpers/handlebars-helpers) and then ask us to whitelist it in Stencil.

**Comment by junedkazi** [comment]
@mrself as @karen-white mentioned above since these handlebar helpers are processed server side for security reasons we cannot allow custom helpers as part of the theme. You can definitely open a PR on the paper-handlerbars repo or on https://github.com/helpers/handlebars-helpers and make a request to pull a certain helper.
