### ISSUE TITLE
Integrate variable to overwrite addthis default account

### ISSUE THREAD

**Issue by fthobe** [bigcommerce/cornerstone#1462]
### Expected behavior
As addthis is already implemented, it makes sense to offer the possibility to overwrite the addthis ID with a custom value. 

### Actual behavior
Bananas, you get the addthis ID bigcommerce has choosen for you in all it's whisdom.

**Comment by bookernath** [comment]
We are actually considering removing our addthis implementation as it seems to cause more problems than it solves. For now, we consider this a "won't fix" given these future plans.

**Comment by fthobe** [comment]
Hi @mattolson, I fully agree that using Addthis in the shop is not an optimal idea as you can as almost all relevant sharing features can be achieved with html only. You can extract the syntax from here: 
https://corp.inntopia.com/tools/share-link-generator/

Do you have any idea what's the next step to replace it or will just be removed?

**Comment by mattolson** [comment]
We don't have any firm timelines for this, but we are aware that we need better social sharing integrations, and this will likely involve removing AddThis.
