### ISSUE TITLE
Video gallery not working as expected

### ISSUE THREAD

**Issue by flair-conor** [bigcommerce/cornerstone#1464]
### Expected behaviour

When clicking a thumbnail, the active video should change to video in the selected thumbnail.

Similar to #1411 

### Actual behaviour

It currently just redirects you to the top of the page as per the `href="#"` in the a tag, and not changing the active iframe video.

### Steps to reproduce behaviour

Go to any product with multiple videos on it and try changing the active video via the thumbnails.

### Step to fix

1) In videos.html change
 `data-video-gallery`
to
 `data-videoGallery`
on line 1

OR

1) In video-gallery.js change 
 `const pluginKey = 'videoGallery';`
to
 `const pluginKey = 'video-gallery';`
on line 40

The js is just trying to call something that doesn't exist, this fixes the issue.

**Comment by karen-white** [comment]
Hey @flair-conor , thanks for submitting this! When you see this issue, could you please confirm the circumstances under which it happens? We're tracking a ticket for it, but we're only able to replicate under very specific conditions, i.e. the product has an option set and has quotation marks in the product name. 

Also, PR welcome, so we can give you the credit for this fix :)

**Comment by flair-conor** [comment]
Oops, apologies. This was for a different project and I've plopped it here instead on accident.
