### ISSUE TITLE
Dropdown cart not showing discounts

### ISSUE THREAD

**Issue by nojacko** [bigcommerce/cornerstone#1467]
### Expected behavior
Cart dropdown to indicate discount.

### Actual behavior
Cart dropdown shows full price for discounted .

### Steps to reproduce behavior

* Set up cart level discount as pictured:
![54776225-8d437080-4c07-11e9-9c14-987dfd6a24fd](https://user-images.githubusercontent.com/1667141/55013634-67d8ad00-4fe1-11e9-8da8-bd9df0190c2a.png)
* Add a few of that product to the cart to trigger discounted item.
* Click "Cart" to show dropdown.

![Screenshot 2019-03-26 at 16 03 15](https://user-images.githubusercontent.com/1667141/55013675-8343b800-4fe1-11e9-88fa-231074964e18.png)

Related to https://github.com/bigcommerce/cornerstone/issues/1466

**Comment by sacr3dc0w** [comment]
@nojacko #1481

**Comment by junedkazi** [comment]
See #1481
