### ISSUE TITLE
Repo link to documentation is broken 

### ISSUE THREAD

**Issue by OllyHodgson** [bigcommerce/cornerstone#1468]
The link to https://stencil.bigcommerce.com/docs on the home page of this repo is broken. Perhaps update it to https://developer.bigcommerce.com/stencil-docs ? 

### Expected behavior

Click the link to https://stencil.bigcommerce.com/docs, and see the Stencil / Cornerstone documentation.

### Actual behavior

Click the link to https://stencil.bigcommerce.com/docs, and see `An error occurred while processing your request. Reference #30.84c64c68.1553887708.576cca2`.

### Steps to reproduce behavior

1. Browse to https://github.com/bigcommerce/cornerstone
2. At the top of the page, click on the link to https://stencil.bigcommerce.com/docs

**Comment by junedkazi** [comment]
@OllyHodgson can you please open a pull request to fix the issue ?

**Comment by OllyHodgson** [comment]
@junedkazi I don't think so - this is in the repository settings, not in code (as far as I know). Someone with the relevant powers would need to log in, hit the edit button in the top right of the screen and update the link:

<img width="403" alt="Screenshot showing the relevant edit button" src="https://user-images.githubusercontent.com/437224/55283793-58c66780-531f-11e9-9d51-a1946d9046ae.png">

**Comment by tatiana-perry** [comment]
@nikita-ahuja :)

**Comment by junedkazi** [comment]
@olegkotyliyak thanks for reporting the issue. The link has been updated.
