### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token - stenci-cli 1.15.8

### ISSUE THREAD

**Issue by sacr3dc0w** [bigcommerce/cornerstone#1470]
### Expected behavior

No uncaught syntax errors. `stencil start` without any problems.

### Actual behavior

Uncaught SyntaxError

### Steps to reproduce behavior

Update to latest stencil-cli, run fresh install of Cornerstone.

### Solution

Revert to stencil-cli 1.15.7.

### System Info

Mac OS 10.14.4
Error occurs in all browsers
Cornerstone 3.4.0, RC3
Stencil-CLI 1.15.8
Node: v6.11.5

### Screenshots

![Screen Shot 2019-04-03 at 7 52 05 AM](https://user-images.githubusercontent.com/5056945/55488894-bab7f300-55e5-11e9-8b06-47120c7255ac.png)
![Screen Shot 2019-04-03 at 7 52 23 AM](https://user-images.githubusercontent.com/5056945/55488895-bab7f300-55e5-11e9-871a-341827982af2.png)

### Related

https://github.com/bigcommerce/stencil-cli/issues/452

**Comment by davidwrpayne** [comment]
Thank you for the report. Our team is working on a fix.

**Comment by bc-zoharmuzafi** [comment]
@sacr3dc0w  we published a new version of stencil-cli (1.15.9) with a fix for the issue.

**Comment by bc-zoharmuzafi** [comment]
we published a new version of stencil-cli (1.15.9) with a fix for the issue.
