### ISSUE TITLE
Add handlebar helper to get custom field value

### ISSUE THREAD

**Issue by LordZardeck** [bigcommerce/cornerstone#1476]
Currently in the context, custom fields are an array of objects. This makes it not possible to cleanly get a specific field value by name. In the template you'd have to loop over the array, and only print the value if the name matches what you want. It would be nice if there was some kind of helper like `{{customField 'my_field_name'}}`, or even a more generic `{{valueFromObjectArray 'name' 'my_field_name'  product.custom_fields}}`

**Comment by bc-zoharmuzafi** [comment]
@LordZardeck Thanks for bringing it up. We will work on implanting this feature. I opened an issue in the relevant repo: https://github.com/bigcommerce/paper-handlebars/issues/33

**Comment by bc-zoharmuzafi** [comment]
Since we moved this issue to paper-handlebars I'm closing that issue.
