### ISSUE TITLE
"Show more" faceted results for facet which contains space returns no results.

### ISSUE THREAD

**Issue by AlexKonoplyanko** [bigcommerce/cornerstone#1487]
### Expected behavior
"Show more" link for filter option should return full list of facets.

### Actual behavior
No results is returned.

### Steps to reproduce behavior
1. In product filtering add filter with name which contains space for example "Design Style" and have more than 10 "Count/Details" so "Show more" link is shown.
2. On category page sidebar find section called "Design Style" and click "show more" link in that filter to see full list for that filter.
3. In popup there will be just heading "Design%20Style" with search input, but no full list of facets.

**Comment by PeteyRev** [comment]
@AlexKonoplyanko Just ran into this today, its an issue with the encoding, `%20` needs to be replaced with `+`, but I believe this needs to be done within the utils library?

**Comment by AlexKonoplyanko** [comment]
@PeteyRev Thanks. Yes, it seems that it should be fixed in api.getPage method and I can't apply fix within a theme.

**Comment by flair-chris** [comment]
@AlexKonoplyanko @PeteyRev you can use the handlebars {{decodeURI all_facets}} instead of {{all_facets}} 
and in the facets list  {{#if facet '===' (decodeURI ../all_facets)}}

then for the IDs you can use {{chop}} and {{dashcase}} or {{hyphenate}} to make it work

**Comment by AlexKonoplyanko** [comment]
@flair-chris Thank you. Your solution resolved the issue.

**Comment by fthobe** [comment]
@karen-white Idem here: weeks / months?

**Comment by fthobe** [comment]
@flair-chris Will this work also in the future if the functionality is restored?

**Comment by flair-chris** [comment]
@fthobe I remember we used something that wasn't encoded and it still worked. So unless it gets drastically changed somehow it should.

**Comment by bc-zoharmuzafi** [comment]
@AlexKonoplyanko seems like the issue resolved, I am closing this ticket
