### ISSUE TITLE
Clean install on Node v10.15.3 fails

### ISSUE THREAD

**Issue by franzese** [bigcommerce/cornerstone#1494]
### Expected behavior

To install application successfully

### Actual behavior

Not an NPM expert, but fails simple NPM installation. A file `https://github.com/bigcommerce-labs/node-sass/releases/download/v3.4.4/darwin-x64-64_binding.node` 404's at the node-sass dependency build
`npm ERR! Failed at the @bigcommerce/node-sass@3.4.4 postinstall script.`

### Steps to reproduce behavior

`git clone git@github.com:bigcommerce/cornerstone.git`
`cd cornerstone`
`npm i`

[npm-output.txt](https://github.com/bigcommerce/cornerstone/files/3170697/npm-output.txt)

**Comment by franzese** [comment]
npm 6.9.0
node v10.15.3

**Comment by jbruni** [comment]
Switch back to Node 8

Node 10 is not supported.

This is sort of a *known issue*:

- https://github.com/bigcommerce-labs/node-sass/pull/5
- https://github.com/bigcommerce/stencil-cli/issues/417

**Comment by flair-chris** [comment]
@jbruni The documentation says tested up to 7.9.0 
Is the documentation behind and we can use 8? Or has it just not been thoroughly tested on 8 yet?

**Comment by jbruni** [comment]
@flair-chris - The documentation at https://developer.bigcommerce.com/stencil-docs/getting-started/installing-stencil says it.

I believe it is behind, because documentation at https://github.com/bigcommerce/stencil-cli#install says tested up to 8.12.0

Where I work, the whole development team is using Node 8, up to latest release, without issues.

We tried Node 10, and it is definitely not supported.

**Comment by flair-chris** [comment]
@jbruni Thanks :)

**Comment by franzese** [comment]
> This is sort of a _known issue_:
> 
> * [bigcommerce-labs/node-sass#5](https://github.com/bigcommerce-labs/node-sass/pull/5)
> * [bigcommerce/stencil-cli#417](https://github.com/bigcommerce/stencil-cli/issues/417)

Would love it if these PRs are approved.

**Comment by mattolson** [comment]
Node 10.x is currently not supported with Stencil CLI. Seems simple, but there are some pretty big changes behind the scenes needed for this. It is something we are looking to fix, but we don't have a defined timeline yet. In the meantime, please use Node 8.x for CLI.

**Comment by Ferrari** [comment]
Hope it could support soon cause Node 10.x already became LTS for a long time. 😢

**Comment by mattolson** [comment]
cc @junedkazi

**Comment by neil473** [comment]
Guidance on the site is now to use 10.16... https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/installing-stencil

I still get following error:
```
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting @bigcommerce/node-sass@git://github.com/bigcommerce-labs/node-sass.git#v3.5.0:
npm ERR! Verification failed while extracting @bigcommerce/node-sass@git://github.com/bigcommerce-labs/node-sass.git#v3.5.0:
npm ERR! sha1-T7a9XAgC2wJdLGeD3DJ7ALZ/ago= integrity checksum failed when using sha1: wanted sha1-T7a9XAgC2wJdLGeD3DJ7ALZ/ago= but got sha512-Mf+zT+KCQfzQw3WY/91XVYnqhtceLCDi4DHl30ZQI+upqIHpYkITuiaCgPvR2b3EgvpAPI3nXT2ZDU7UW8S6uQ== sha1-c/anQLXkh2Vjg8SpG1hIXTD21pU=. (314072 bytes)
```

anyone any clues?

**Comment by neil473** [comment]
> Guidance on the site is now to use 10.16... https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/installing-stencil
> 
> I still get following error:
> 
> ```
> npm ERR! code EINTEGRITY
> npm ERR! Verification failed while extracting @bigcommerce/node-sass@git://github.com/bigcommerce-labs/node-sass.git#v3.5.0:
> npm ERR! Verification failed while extracting @bigcommerce/node-sass@git://github.com/bigcommerce-labs/node-sass.git#v3.5.0:
> npm ERR! sha1-T7a9XAgC2wJdLGeD3DJ7ALZ/ago= integrity checksum failed when using sha1: wanted sha1-T7a9XAgC2wJdLGeD3DJ7ALZ/ago= but got sha512-Mf+zT+KCQfzQw3WY/91XVYnqhtceLCDi4DHl30ZQI+upqIHpYkITuiaCgPvR2b3EgvpAPI3nXT2ZDU7UW8S6uQ== sha1-c/anQLXkh2Vjg8SpG1hIXTD21pU=. (314072 bytes)
> ```
> 
> anyone any clues?

this seemed to work if anyone else has this:
https://github.com/bigcommerce/stencil-cli/issues/250#issuecomment-255792157

**Comment by junedkazi** [comment]
Please use the latest version of stencil-cli which should support node 10. We are also working on adding support for node 12 soon. Please open a new issue if you run into any issues with the latest cli version on node 10.
