### ISSUE TITLE
carousel-content.html change h1 to h2 

### ISSUE THREAD

**Issue by bigmadness** [bigcommerce/cornerstone#1500]
<div class="heroCarousel-content{{#unless show_background}} heroCarousel-content--empty{{/unless}}">
    <h2 class="heroCarousel-title">{{{heading}}}</h2>
    <p class="heroCarousel-description">{{{text}}}</p>
    {{#if button_text}}
        <span class="heroCarousel-action button button--primary button--large">{{button_text}}</span>
    {{/if}}
</div>

**Comment by bc-zoharmuzafi** [comment]
@bigmadness I couldn't reproduce the issue. Will you be able to upgrade to the latest cornerstone and see if this is resolved? If you still experience this issue please add some more information about the issue and steps to reproduce.
