### ISSUE TITLE
can not update cart quantity

### ISSUE THREAD

**Issue by laanlabs** [bigcommerce/cornerstone#1503]
this is broken on all releases since 3.2.0 -- 3.2.0 works correctly

### Expected behavior
cart quantity updates on arrow or manual entry

### Actual behavior
ajax script return error from /remote/v1/cart/update

### Steps to reproduce behavior

clean checkout of any version since 3.2.0 will not allow card quantity update

**Comment by bc-zoharmuzafi** [comment]
@laanlabs I couldn't reproduce the issue (cornerstone 3.5.0). Will you be able to upgrade to the latest cornerstone and comment on this issue if this issue was resolved or not?

**Comment by brandonjp** [comment]
I can't contribute to current version, but I'm having a hell of a time trying to patch a customized site stuck on v1.8.1 where the quantity increment buttons are broken. No script errors.  If anyone has recollection of past edits that might give me clues, I'm listening!

**Comment by carsonreinke** [comment]
@brandonjp [This?](https://github.com/bigcommerce/cornerstone/pull/1418)
