### ISSUE TITLE
Faceted search issue when apply a category filter on search results page

### ISSUE THREAD

**Issue by ElynJin** [bigcommerce/cornerstone#1504]
On search results page, I have some filters including category filter
![image](https://user-images.githubusercontent.com/23391710/58111319-19412c80-7ba6-11e9-9102-87a949ce9957.png)

![image](https://user-images.githubusercontent.com/23391710/58111110-b18ae180-7ba5-11e9-9197-1510c7b563f7.png)

![image](https://user-images.githubusercontent.com/23391710/58110970-607aed80-7ba5-11e9-94d4-7834a037c8c7.png)

Other category filters can applied correctly, except the "Books" category

"Articles" filter
http://localhost:3000/search.php?search_query=ocean&section=product&_bc_fsnf=1&category=25
![image](https://user-images.githubusercontent.com/23391710/58111645-b9975100-7ba6-11e9-86a5-43f3b9530a16.png)

After I applied the category filter "Books", the active filter is empty

http://localhost:3000/search.php?search_query=ocean&section=product&_bc_fsnf=1&category=24
![image](https://user-images.githubusercontent.com/23391710/58111443-4db4e880-7ba6-11e9-9e08-4791fb796193.png)

![image](https://user-images.githubusercontent.com/23391710/58110808-10039000-7ba5-11e9-943b-8c39d99bb7ce.png)

**Comment by hpatel3006** [comment]
@karen-white please advise on this issue

**Comment by karen-white** [comment]
@ElynJin I'm having some trouble replicating this issue on a sandbox store. Is there anything different about the Books category, from what you can see?

@hpatel3006 Are you also experiencing the same issue? If so, any details you can provide would be helpful for troubleshooting!

**Comment by bc-zoharmuzafi** [comment]
@ElynJin we couldn't reproduce this issue. If you're still experiencing this issue or have any new information please open the issue.
