### ISSUE TITLE
Dev doc, non npm tutorial not synced with cornerstone repo

### ISSUE THREAD

**Issue by phpmaps** [bigcommerce/cornerstone#1509]
### Expected behavior

Doc and repo should be clear on how to customize with JS.  Doc should reference a file that exists in Cornerstone.

### Actual behavior

There is no more ```blog.js``` file in the current repo.

### Steps to reproduce behavior

Try to follow this doc.  Note that not much makes sense b/ ```blog.js``` file is missing.   https://developer.bigcommerce.com/stencil-docs/custom-javascript-implementations/basic-non-npm-tutorial

**Comment by bc-zoharmuzafi** [comment]
@phpmaps Thank you for pointing that out. Our team is working on updating the docs, and will notify once the docs are updated. @nikita-ahuja

**Comment by nikita-ahuja** [comment]
Hi @phpmaps  - the docs have been updated. 

That article should now redirect to the updated version called 'Customizing Javascript.' (https://developer.bigcommerce.com/stencil-docs/development-quickstart/customizing-javascript)
