### ISSUE TITLE
Bulk pricing stop working recently

### ISSUE THREAD

**Issue by tvlgiao** [bigcommerce/cornerstone#1517]
### Expected behavior

**Bulk pricing** or **Buy in bulk and save** need to remain showing when product option is changed.

### Actual behavior

**Bulk pricing** or **Buy in bulk and save** is disappeared immediately when the product page is finished loading.

### Steps to reproduce behavior

1. Edit a product and set bulk pricing for example: http://prntscr.com/o0qc8e
2. Create a new **variant option** with type **Rectangle List** and 3 options S, M, L and set **default** to S. Screenshot: http://prntscr.com/o0qh2o and http://prntscr.com/o0qeoy
3. Apply Cornerstone theme to live.
4. View the product page on the front-end with Cornerstone theme applied, you will see the link **"Buy in bulk and save"** show up but immediately disappear when the page is finished loading.

**This issue seems to appear recently and affects to all themes**

**Comment by karen-white** [comment]
Thanks for reporting this @tvlgiao . This seems consistent with an issue we're tracking through an internal ticket. We'll keep you updated on a fix 👍

**Comment by bc-zoharmuzafi** [comment]
@tvlgiao This was a backend issue and it has been fixed. It should roll out to all stores in the next few days.

**Comment by tvlgiao** [comment]
@bc-zoharmuzafi Thanks for the fix. I've seen some stores using our themes has been returned to normal.
