### ISSUE TITLE
Why the space after hash symbol in IF statement?

### ISSUE THREAD

**Issue by brandonjp** [bigcommerce/cornerstone#1528]
I was noticing 3 places that have a whitespace after the octothorpe in an if statement like this: 
````{{# if can_modify}}````

https://github.com/bigcommerce/cornerstone/blob/3207cae9eb89d14da3129e59f95b119b8ad0bc82/templates/components/cart/content.html#L79

https://github.com/bigcommerce/cornerstone/blob/3207cae9eb89d14da3129e59f95b119b8ad0bc82/templates/components/cart/content.html#L99

https://github.com/bigcommerce/cornerstone/blob/3207cae9eb89d14da3129e59f95b119b8ad0bc82/templates/components/cart/content.html#L119

I was curious if this was just a typo or if it has significance.  

Also curious why this doesn't seem to have any negative effects.  My expectation was that it would throw a Handlebars error, but that doesn't seem so.  

(I was trying to fix a problem with my Quantity increment buttons not working, but this didn't seem to fix it 😞)

**Comment by carsonreinke** [comment]
It just looks old, you should put in a PR to fix

**Comment by bc-zoharmuzafi** [comment]
@brandonjp Thank you for bringing that up, I opened a pr to remove those whitespaces. From local test that I made it didn't seems to negatively effect the if statements.
