### ISSUE TITLE
How to track the change of order status in bigcommerce?

### ISSUE THREAD

**Issue by mahammad13** [bigcommerce/cornerstone#1543]
I want to know from which order status to current order status is changed for an particular order. 
I know to know previous order status of particular order

Please help me on this

Thanks,
Mahammad

**Comment by bookernath** [comment]
Hi @mahammad13 , this request doesn't really have anything to do with Cornerstone - but you can consider using our webhooks which are documented here:

https://developer.bigcommerce.com/api-docs/getting-started/webhooks/about-webhooks
