### ISSUE TITLE
getImageSrcset is not working on localhost

### ISSUE THREAD

**Issue by ocvninfo** [bigcommerce/cornerstone#1548]
I've updated **imageSrcset** for my template. But it's not working on localhost. All images are not showing up. 
However, it's still working correctly when i push the template to live site.
So how can i fix this?

**Comment by bookernath** [comment]
Hi @ocvninfo , you probably need to update stencil-CLI to get this helper.

Try `npm install -g @bigcommerce/stencil-cli` to get the latest update.

**Comment by ocvninfo** [comment]
@bookernath  Thanks! I forgot that.
