### ISSUE TITLE
One-Page Checkout Whites Out On IE11

### ISSUE THREAD

**Issue by sacr3dc0w** [bigcommerce/cornerstone#1557]
### Expected behavior

Checkout to function in the land of Mordor (IE11).

### Actual behavior

White out. No errors seem to occur according to the console.

### Steps to reproduce behavior

Add item to cart in IE11, proceed to checkout.

<img width="2160" alt="Screen Shot 2019-08-08 at 9 08 30 AM" src="https://user-images.githubusercontent.com/5056945/62719406-bc8f2a00-b9bc-11e9-951c-287191dc3a89.png">

**Comment by asiejnapsc** [comment]
I see this was closed and also from a year ago, but I'm having this exact issue on one of my stores. Do you remember what the cause of this was? Would help me troubleshoot. Thanks!
