### ISSUE TITLE
Conflicting jQuery dependency with Zurb Foundation

### ISSUE THREAD

**Issue by carsonreinke** [bigcommerce/cornerstone#1587]
### Expected behavior

Everything works perfectly because dependencies are defined.

### Actual behavior

foundation-sites does not list jQuery dependency except in some random bower file.

[foundation-sites v5.5.3](https://github.com/foundation/foundation-sites/blob/v5.5.3/js/foundation/foundation.js#L345) uses features of jQuery <3.0.  Specifically, the [`.load()`](https://api.jquery.com/load-event/) method which was removed in jQuery 3.0.  Currently jQuery ^3.4.1 is installed.

### Steps to reproduce behavior

N/A

**Comment by wwwdepot** [comment]
See jQuery migrate files?

https://github.com/bigcommerce/cornerstone/blob/4e67c81ba03189123e943bf2e54059ebb86499d3/assets/js/theme/global/jquery-migrate/event.js#L1-L7

**Comment by carsonreinke** [comment]
@wwwdepot Whoops!  😉

**Comment by carsonreinke** [comment]
I am actually mystified how this works with WebPack 4.  You may or may not get the "migrated" version of jQuery, depending on some things.
