### ISSUE TITLE
AMP iframe issue on PDP

### ISSUE THREAD

**Issue by flair-chris** [bigcommerce/cornerstone#1607]
### Expected behavior
To have a product page with add to cart buttons and options

### Actual behavior
the carousel and descriptions appear but the amp-iframe is blocked, this error is in the console:
Origin of <amp-iframe> must not be equal to container  <amp-iframe height=​"400" width=​"250" layout=​"responsive" sandbox=​"allow-forms allow-pointer-lock allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals" resizable src=​"https:​/​/​cornerstone-light-demo.mybigcommerce.com/​products.php?type=amp_product_options&productId=97" class=​"i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-error i-amphtml-layout" i-amphtml-layout=​"responsive" scrolling=​"no" frameborder=​"0">​…​</amp-iframe>​ if allow-same-origin is set. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.
vf @ error.js:195

### Steps to reproduce behavior
Navigate to https://cornerstone-light-demo.mybigcommerce.com/amp/all/tiered-wire-basket/

**Comment by obrien-k** [comment]
When testing this page using Google's AMP Validator tool I am seeing it pass: https://cornerstone-light-demo.mybigcommerce.com/amp/all/tiered-wire-basket/

Find additional context for why this happens when accessing an AMP-based page directly in #1103

**Comment by flair-chris** [comment]
thanks @obrien-k,
I hadn't seen your comment. This does explain the reason thanks
