### ISSUE TITLE
akamai image manager and .webp

### ISSUE THREAD

**Issue by calscables** [bigcommerce/cornerstone#1624]
In this article:

https://support.bigcommerce.com/s/article/Optimizing-Your-Images

It mentions:

"It will also retroactively optimize images you have uploaded in the past that have not previously been optimized. Akamai Image Manager may save images as .webp instead of jpeg."

Is this still a feature or has it been removed? I don't notice my images using .webp

Sorry for not using the correct issue format, i just need to get this cleared up.

**Comment by wwwdepot** [comment]
AIM does optimizes images without changing the image extension. You can check image's response content-type under Network tab in Chrome Devtools.

**Comment by calscables** [comment]
Cool, but what happened with akamai image manager and .webp (fallback with png/jpeg)?

**Comment by wwwdepot** [comment]
Correct, browsers that do not support webp, it will fallback with the original image.

**Comment by calscables** [comment]
Just to clarify, does the cornerstone theme use akamai image manager? @wwwdepot

**Comment by wwwdepot** [comment]
Yes, by using `cdn` handlerbar helper, see https://developer.bigcommerce.com/stencil-docs/storefront-customization/theme-assets

**Comment by calscables** [comment]
@wwwdepot I see now. After looking through the theme, it appears that only product images on the home + category page are returning as .webp. 

The images on the product page itself (zoom images) are returning as a .png (or what ever file format it was uploaded as, possibly). 

And the category images are turning as .jpeg (maybe akamai image manager see's jpeg as a better file format than a .webp image).

Thanks for helping me clear this up.

**Comment by calscables** [comment]
Which is interesting (the category image and zoom image), .webp is still a smaller file size than jpeg, why is jpeg still being served. I'll do some digging myself to find out why. probably because of the parameters passed into the image's cdn handlebar helper.

**Comment by PeteyRev** [comment]
@calscables this should be closed

**Comment by junedkazi** [comment]
Based on conversation this seems resolved. So I am going to close this issue.
