### ISSUE TITLE
BLANK!  server/localhost/browser is only loading a blank page

### ISSUE THREAD

**Issue by brandonjp** [bigcommerce/cornerstone#1638]
### Expected behavior
When stencil server is running, loading a URL should display the relevant theme/template files. 

### Actual behavior
Only a blank page is displayed in the browser. 

### Steps to reproduce behavior
When I clone this repo then run `npm install` & `stencil start` -- the theme loads perfectly in the browser at http://localhost:3000 (& 3001).  But if I stop the server, when I run `stencil start` again, I'm only getting a blank page in the browser.   If I do a new clone (into a new folder) and run `npm install` & `stencil start` again, it works fine.  But re-cloning and npm-installing is required EVERYTIME! 

#### What I've Tried...
I'm using Node Version: v10.17.0.  I've tried 3 other major node versions. I've tried wiping out the `node_modules` directory. I've tired `npm update` & clearing npm cache.  But it's always loading a blank page.  There are no errors in the terminal (it is successfully starting the server & watching files).  This happens in Chrome, Firefox, Safari, iOS Safari

Has anyone else seen this issue?  Any suggestions on how to troubleshoot?
Thanks

![CleanShot 2020-06-10 at 14 05 41@2x](https://user-images.githubusercontent.com/199599/84308341-f7557780-ab23-11ea-811f-35b46b276502.png)

* RE: https://github.com/bigcommerce/cornerstone/issues/1638
* RE: https://github.com/bigcommerce/stencil-cli/issues/606
* RE: https://support.bigcommerce.com/s/question/0D54O00006TlSVBSA3/blank-serverlocalhostbrowser-is-only-loading-a-blank-page

**Comment by junedkazi** [comment]
I don't think this is a cornerstone issue. Let's discuss this in `stencil-cli` repo.
