### ISSUE TITLE
Category Images Are Too Small on High Res Mobile Devices

### ISSUE THREAD

**Issue by msevette** [bigcommerce/cornerstone#1645]
### Expected behavior
Should expand to full width of viewing screen in both portrait and landscape modes. NOTE: There are no issues on lower resolution mobile devices.

### Actual behavior
Images are left-aligned and only expand to approximately 50% of viewing screen in portrait or landscape modes. Larger images do not change behavior, other than longer load times. Settled on adding center-align class in order to center the small category images. Would prefer to have the option of category images that are full-width.

**Comment by bookernath** [comment]
Fixed in https://github.com/bigcommerce/cornerstone/pull/1640
