### ISSUE TITLE
Products not adding to cart from localhost

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/cornerstone#1653]
### Expected behavior
Product should be added to cart when running theme locally

### Actual behavior
Nothing gets added to cart

### Steps to reproduce behavior
Node v8.16.1
Stencil 1.21.2
Run latest cornerstone master branch using stencil cli
`stencil start`
Load `localhost:3000`. Navigate to product page. Add to cart:

![image](https://user-images.githubusercontent.com/2486712/77266825-04766f00-6c77-11ea-8f28-5d7e46b61316.png)

This started happening sometime in the last few days. It's not a cornerstone issue, since it's doing it with my own custom theme as well, but I wasn't sure where else to post it.

UPDATE - I tried updating to node version 10.15.0 and stencil version 1.23.1. That did not fix the problem.

**Comment by junedkazi** [comment]
@flyingL123 as I mentioned in the cli issue. Please get the latest 2.0 and it should be fixed in that version.
