### ISSUE TITLE
Product Review Text Contents Broken - HTML Symbols

### ISSUE THREAD

**Issue by mattcoy-arcticleaf** [bigcommerce/cornerstone#1660]
### Expected behavior
Leaving a review like `This product isn't great! It could be better & I think I should return it.` should yield this exact text on the store when submitted.

### Actual behavior
The text gets converted like this: `This product isn&#039;t great! It could be better &amp; I think I should return it.`

### Steps to reproduce behavior
Leave a review containing symbols on a store running Cornerstone 4.5 (or really any Cornerstone version).

<img width="483" alt="reviews-with-symbols" src="https://user-images.githubusercontent.com/47044676/79879763-f87beb00-83a3-11ea-9133-9163b59acb5e.png">

#### Note: 
I tried switching `{{ text }}` to `{{{sanitize text}}}` and this solved it, but then we lose the nl2br helper which is probably important to keep. `{{{nl2br (sanitize text)}}}` does not work.

**Comment by Tiggerito** [comment]
I also found {{{nl2br text}}} did not work. Seems nl2br is encoding as well as adding <br/>s

**Comment by sacr3dc0w** [comment]
#1665

**Comment by danvisionarybrands** [comment]
We encountered the same issue. We found that changing the handlebars value to simply, {{{ text }}} , resolved the issues with the HTML characters not being escaped properly.

**Comment by mattcoy-arcticleaf** [comment]
Closing out as this was resolved in #1665
