### ISSUE TITLE
Hero carousel images stretched on large screens

### ISSUE THREAD

**Issue by rowleyaj** [bigcommerce/cornerstone#1677]
### Expected behavior
Setting `homepage_stretch_carousel_images` to false should prevent the carousel images being stretched on large screens

Help pages referenced:
https://support.bigcommerce.com/s/article/Carousel#carousel-dimensions
https://support.bigcommerce.com/s/article/Fixing-Distorted-Images#faq

### Actual behavior
It stretches the image and letterboxes due to `object-fit: cover` regardless of the setting

### Steps to reproduce behavior
Load page on a large browser window

---

I've tried to include further information below, as to what I believe the cause of this issue is:

The setting controls the addition of the class `stretch` in carousel.html:
https://github.com/bigcommerce/cornerstone/blob/d681ca929f24243a2284c15e4513fedc989686ec/templates/components/carousel.html#L13 

Searching for stretch in the repo:
```
$ ag stretch
config.json
57:    "homepage_stretch_carousel_images": false,
384:        "homepage_stretch_carousel_images": false,

schemaTranslations.json
926:  "i18n.AllowImageToStretchOn": {
927:    "default": "Allow image to stretch on large screens",

schema.json
980:        "label": "i18n.AllowImageToStretchOn",
982:        "id": "homepage_stretch_carousel_images"

templates/components/carousel.html
13:        <div class="heroCarousel-slide {{#if ../theme_settings.homepage_stretch_carousel_images}}stretch{{/if}} {{#if @first}}heroCarousel-slide--first{{/if}}">

assets/scss/components/stencil/heroCarousel/_heroCarousel.scss
103:        &.stretch {
```

The only place I can find this class configured is in `assets/scss/components/stencil/heroCarousel/_heroCarousel.scss`

https://github.com/bigcommerce/cornerstone/blob/d681ca929f24243a2284c15e4513fedc989686ec/assets/scss/components/stencil/heroCarousel/_heroCarousel.scss#L103-L107

but this compiles to a selector that requires `compat-object-fit`: `.heroCarousel-slide.compat-object-fit.stretch` so I'm not sure this is the right one to be looking at?

frontend code isn't my speciality so i might be way off the mark here, but this functionality appears to have been changed with this commit https://github.com/bigcommerce/cornerstone/commit/970d0e5ca774bcec5cf8226a6672b2d576fbac53

I'd appreciate some assistance determining what size images are best for the hero carousel. what's the aspect ratio that is best, and therefore what width and height should i use? would I upload the largest width i'd like to support and then have the akamai image manager modify them to the appropriate width? does the carousel automatically support the height being set appropriately for this?

If i'm understanding this correctly, I think I'd still like to avoid using `object-fit: cover` if possible as this will lead to clipping and potentially losing content from banners we add to the carousel?

Any help appreciated, but I'm also open to raising a PR if someone could point me in the right direction.

**Comment by junedkazi** [comment]
This should be fixed in cornerstone 4.8
