### ISSUE TITLE
Can't Access 403 Page. Stencil server gives 403 but renders 500 in browser.

### ISSUE THREAD

**Issue by brandonjp** [bigcommerce/cornerstone#1686]
### Expected behavior
When not logged in, accessing the URL of a product that requires login should display the 403 template in the browser.

### Actual behavior
The browser is displaying a 500 error.

### Steps to reproduce behavior
When I access a product that requires login, on the production server this renders the 403 template page.  On my localhost, the stencil server gives 403 in the terminal, but the browser reports 500 error.  I'm trying to customize the 403 page, but can't access it in the browser.  

Any insights on why this might be & how to remedy it? 

![2LRx7gCt2KrWFma1B1Kh8PmSipQAuqSSpi5RZbQ8](https://user-images.githubusercontent.com/199599/84306986-de4bc700-ab21-11ea-973b-fcc62b544304.jpg)

 * RE: https://github.com/bigcommerce/stencil-cli/issues/605
 * RE: https://github.com/bigcommerce/cornerstone/issues/1686 
 * RE: https://support.bigcommerce.com/s/question/0D54O00006TlRWHSA3/cant-access-403-page-stencil-server-gives-403-but-renders-500-in-browser

**Comment by junedkazi** [comment]
@brandonjp this is not a cornerstone issue so I am going to close this one. We can continue digging into it in stencil cli
