### ISSUE TITLE
CORS Errors on Safari 13.1 when fetching native checkout scripts from https://cdn11.bigcommerce.com/shared/microapp/checkout/dist/

### ISSUE THREAD

**Issue by Mikhail-MM** [bigcommerce/cornerstone#1690]
Hello,

We've been seeing some issues after implementing a 'piggyback' script on the native One Page Checkout - we're implementing some custom fetch requests inside of a Script Tag in cornerstone's `checkout.html`, and we've noticed a small percentage of instances where these requests simply aren't going through. 

After attaching a Sentry instance on the checkout page, we've found that browsers running Safari 13.1 are uniquely returning a Promise rejection error when fetching bigcommerce's native /microapp/ domain scripts:

![image](https://user-images.githubusercontent.com/25877260/84608165-197e2b00-ae7f-11ea-9349-7fdfb54b7260.png)

![image](https://user-images.githubusercontent.com/25877260/84608197-3dda0780-ae7f-11ea-8254-f2031dcd90f1.png)

Can you please advise here? This is breaking all of our customizations on the client's Checkout Page, it seems like there are critical scripts that are failing to be fetched from BigCommerce, yet the checkout page itself seems to load properly and the customers are able to actually check out. 

I thought that this would be an issue on this particular client's site, yet we're seeing it on others. Are you aware that there are CORS issues happening on Safari 13.1? Has this been picked up by the support team from any other instances or is this something we alone are seeing?

Thanks for your time in reviewing this issue. Look forward to hearing back on any possible causes such as DNS or others?

**Comment by bookernath** [comment]
This should be resolved as of around a month ago, so I'll close it out. If you continue to see issues with checkout, https://github.com/bigcommerce/checkout-sdk-js might be the better place to raise them.
