### ISSUE TITLE
Suggested cart products no longer appearing

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/cornerstone#1716]
### Expected behavior
After adding an item to cart, on the mobile view, there should be suggested products that appear in the preview.

### Actual behavior
There are no suggested products.

### Steps to reproduce behavior
Add an item to cart on the mobile cornerstone view.

I no longer see any suggested products being returned as part of the stencil data object. Did something change recently that may have unintentionally removed these?

**Comment by flyingL123** [comment]
Even on a fresh install of Cornerstone, if I add to cart, when I am redirected to a URL like this:

https://localhost:3000/cart.php?suggest=40a95f7f-2094-41aa-83ac-f82d2f69c026 the stencil data does not contain a key for `suggested_products` like it used to.

![image](https://user-images.githubusercontent.com/2486712/86955204-34ae2480-c125-11ea-9a1b-939e5db31f14.png)

**Comment by sacr3dc0w** [comment]
This is occurring on all our storefronts and the Cornerstone Demo storefront as well.

https://cornerstone-light-demo.mybigcommerce.com/

**Comment by flyingL123** [comment]
@sacr3dc0w do you know if anybody has read this or acknowledged the issue? @bookernath any idea what's going on?

**Comment by bookernath** [comment]
Hey all,

Unfortunately we uncovered some serious issues with the implementation of this feature which caused us to have to remove it:

https://developer.bigcommerce.com/changelog#posts/cart-suggestions-removed-from-stencil-context-cart-model

We are going back to the drawing board with this one, and we hope to re-surface it in the future together with a new, much improved recommendations engine.

**Comment by flyingL123** [comment]
@bookernath thanks for the info.
