### ISSUE TITLE
Checkout error when using Chrome on iOS or Mac 

### ISSUE THREAD

**Issue by oggede** [bigcommerce/cornerstone#1787]
Hi

I'm getting a number of customer lately having problems checking out when using Chrome on a Mac or iOS device.

### Expected behavior

Checkout page works fine.

### Actual behavior

Checkout page gets stuck on "loading". Customers can not checkout when using Mac or iOS version of Chrome. Page just hangs or gets stuck. Customer can not go complete checkout.

### Steps to reproduce behavior

Use browser Chrome IOS 57.0.2987.137

Or

Chrome Macintosh 84.0.4147.125

Add something to cart and try and checkout.

**Comment by bc-as** [comment]
@oggede Is this still an issue for you?  Do you have any additional details / screenshots / etc that can help us out here?

**Comment by oggede** [comment]
> @oggede Is this still an issue for you? Do you have any additional details / screenshots / etc that can help us out here?

Hi. I have updated to Version: 4.10.0. No reported problems as of yet. Unfortunately I don't have a Mac to test. Perhaps close this case for now. I will keep an eye out if I get more reports from customers. Thanks.

**Comment by bc-as** [comment]
@oggede thanks!  feel free to reopen this if it pops up again.
