### ISSUE TITLE
Stencil Bundle Error

### ISSUE THREAD

**Issue by VisionsDeveloper** [bigcommerce/cornerstone#1796]
Hello Guys,

We have facing some issue while creating the bundle for some projects. Cornerstone Version-4.8.0

![Screenshot_1](https://user-images.githubusercontent.com/52342724/91303832-33fd4a80-e7c6-11ea-813e-b404c17e9042.png)
![Screenshot_1](https://user-images.githubusercontent.com/52342724/91303864-3cee1c00-e7c6-11ea-8e69-62dab7f725fb.png)

Thanks,
VD

**Comment by VisionsDeveloper** [comment]
Hello Guys,

We have faced some issues while creating the bundle for some projects. Cornerstone Version-4.8.0

![Screenshot_1](https://user-images.githubusercontent.com/52342724/91304245-cf8ebb00-e7c6-11ea-9f5d-9d69dcdb6495.png)

Thanks,
VD

**Comment by junedkazi** [comment]
I believe this is resolved by https://github.com/bigcommerce/stencil-cli/pull/622. Please use the latest 3.x version of stencil cli
