### ISSUE TITLE
Issue with checkout and recaptcha

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/cornerstone#1841]
Cornerstone team, can you please review this issueI posted in the checkout-sdk repo? It doesn't seem to be getting any attention, but seems to be a very obvious, reproducible bug. I am completely unable to place an order in development when I have recaptcha settings enabled in my store, as detailed in the issue:

https://github.com/bigcommerce/checkout-sdk-js/issues/933

It may not be an sdk issue, so I wanted to post here as well. Can anybody help with this? It's making checkout development extremely challenging.

**Comment by junedkazi** [comment]
@flyingL123 I am going to close this in favor of the original checkout issue since that is the right place to discuss this issue.
