### ISSUE TITLE
Carousel images not loading due to Lazy Load bug on iPad

### ISSUE THREAD

**Issue by enkota** [bigcommerce/cornerstone#1954]
### Actual behavior
Carousel images not loading on iPad OS 14.3. First image loads fine, but images on remaining slides no longer load.

After testing this appears to be related to lazy load. Disabling on the slides beside the first will bring them back.

### Steps to reproduce behavior

Issue also occurs on the demo site - https://cornerstone-light-demo.mybigcommerce.com

![IMG_0149](https://user-images.githubusercontent.com/13979799/104931626-8ff78400-599e-11eb-8dea-56cdeb0dda9c.PNG)

**Comment by yurytut1993** [comment]
Hello @enkota 
Can you please give more information to reproduce? Visited your test store on iPad iOS 14.3 using both Safari and Chrome - works fine. Previously visited on iOS 14.2 - also works

**Comment by enkota** [comment]
Hey @yurytut1993 - it's a strange one. Tested this morning on a colleagues device and they can't recreate. Happy to close this for now. Done the usual clear cache etc. I can see the images loaded in the inspector, so most likely device specific. 

Happy to close for now. Will open if I find out any more, cheers.
