### ISSUE TITLE
When choosing a variant page scrolls to bottom

### ISSUE THREAD

**Issue by fthobe** [bigcommerce/cornerstone#1973]
### Expected behavior
When picking a variant no moving of the viewport should be initiated

### Actual behavior
When choosing a product variant window scrolls to the bottom. 

### Steps to reproduce behavior
View below gif

![Screen Recording 2021-01-26 at 12 20 13](https://user-images.githubusercontent.com/579379/105838957-1af50180-5fd1-11eb-8698-b7d18890f8d8.gif)

**Comment by BC-tymurbiedukhin** [comment]
Will be fixed in Cornerstone 5.1.0 release

**Comment by fthobe** [comment]
Duplicate issue #1957
