### ISSUE TITLE
Login Form redirect doesn't redirect user

### ISSUE THREAD

**Issue by AndrewBarber** [bigcommerce/cornerstone#1981]
### Expected behavior
[According to the docs](https://developer.bigcommerce.com/stencil-docs/developing-further/modifying-forms#login-form-redirect) using the following code should redirect a user upon login to `/shop-all`
```
<input type="hidden" id="redirect_to" name="redirect_to" value="/shop-all">
```

### Actual behavior
User is redirected to account or cart (if they have items in their cart)

### Steps to reproduce behavior
- Enter the line  `<input type="hidden" id="redirect_to" name="redirect_to" value="/shop-all">` into the form.html login form.
- Run stencil
- Log in to your BC Store

**Comment by AndrewBarber** [comment]
Seems like this is specific to us, I am able to get this to work on a sandbox.

**Comment by HATECORO** [comment]
I have same problem,it seem like about theme version

**Comment by HATECORO** [comment]
> 似乎这是我们特有的，我能够在沙盒上使用它。

Did you resolve it ?
