### ISSUE TITLE
price.html

### ISSUE THREAD

**Issue by obrien-k** [bigcommerce/cornerstone#2038]
### Expected behavior
Use https for all links

### Actual behavior

`<meta itemprop="availability" itemtype="http://schema.org/ItemAvailability" 
                	content="http://schema.org/{{#if product.pre_order}}PreOrder{{else if product.out_of_stock}}OutOfStock{{else if product.can_purchase '===' false}}OutOfStock{{else}}InStock{{/if}}">`

Uses http for schema ?

### Steps to reproduce behavior

Review price.html

**Comment by rowleyaj** [comment]
this can be closed as linked PR has been merged
