### ISSUE TITLE
stylelint

### ISSUE THREAD

**Issue by apalysPSC** [bigcommerce/cornerstone#2106]
My team is upgrading our cornerstone sites from 5.7.1 to 6.0.0. We noticed after creating a pull request in Github that there are a lot of eslint errors, which are being caused by our stylesheets. I know in version 6.0.0 the scss lint was replaced with stylelint- is that what is causing all these errors? Also, is there a way to disable this? If we can't disable this, is it affecting our code at all? My team would like to eventually reformat and correct these errors, but at the moment there are too many to tackle and we have other projects we need to see to.

**Comment by BC-krasnoshapka** [comment]
@apalysPSC your are totally right. latest Cornerstone release 6.0.0 has breaking change - new stylelint rules. if you decided to upgrade to this version, you can fix your custom styles when you have time. automatic fix via `stylelint:fix` command can help.

**Comment by apalysPSC** [comment]
Thanks for your response! Where would you run that command?

**Comment by BC-krasnoshapka** [comment]
Try to run it in the cornerstone theme folder. Most likely you need to run `npm install` before to install all dependencies.

**Comment by apalysPSC** [comment]
I ran npm install and still got that the command could not be found
![Screenshot (48)](https://user-images.githubusercontent.com/81984132/128879240-632cd5a0-601d-44c0-bc69-9f8364cf9566.png)

**Comment by apalysPSC** [comment]
That worked! Thank you for the help!
