### ISSUE TITLE
Checkout: on iPhone with 'Display Zoom' setting enabled:  Payment fields 'cut off' / inaccessible 

### ISSUE THREAD

**Issue by MisterOctober** [bigcommerce/cornerstone#2299]
### Expected behavior
Payment fields would be accessible on iPhone regardless of whether user has Display Zoom enabled in Settings

### Actual behavior
When a user on iPhone has Display Zoom enabled, **payment fields are "cut off" on the right side of the screen** and not accessible
![cornerstone-iphone-display-zoom-checkout-cut-off](https://user-images.githubusercontent.com/39059700/207994956-b78944af-7db8-4f39-a9a0-588cc38d3ded.png)

It appears that this prevents any user with Display Zoom enabled, from completing a purchase on our site

### Steps to reproduce behavior
Using a physical iPhone, go to settings -> display + brightness -> Display Zoom -> select Larger Text  
iPhone will restart, after which Display Zoom will be enabled 
Navigate to checkout page -> payment information

Note: this issue appears (and the above screenshot was taken ) when vanilla Cornerstone (with no customizations) is the theme on our site

**Comment by BC-krasnoshapka** [comment]
hi @MisterOctober 
if you're using BigCommerce's open source checkout, please forward this issue to https://github.com/bigcommerce/checkout-js

**Comment by MisterOctober** [comment]
@BC-krasnoshapka 

Thanks for the heads up!  
re-filed at the specified repo `checkous-js`, new issue number is #1129

closing this issue for now
