### ISSUE TITLE
Experiencing errors trying to develop theme

### ISSUE THREAD

**Issue by Ctucker9233** [bigcommerce/cornerstone#2388]
### Expected behavior
I followed the stencil cli setup instructions, and the instructions to start developing a theme. I expected there to be no problems, because the documentation didn't say I needed to do anything extra.

### Actual behavior
I get errors. Some I could resolve, but this one I got stuck on.
Module not found: Error: Can't resolve 'lazysizes' in 'C:\Users\ctucker\Desktop\Cornerstone-6.12.0' resolve 'lazysizes' in 'C:\Users\ctucker\Desktop\Cornerstone-6.12.0'

Note: There is no node modules folder when you download the theme files from bigcommerce, and as far as I'm aware, there isn't supposed to be one. Since it appears these are required for the stencil commands to work, I'm confused as to where I need to put them.

### Steps to reproduce behavior
Create copy of Cornerstone theme in bigcommerce
Download theme files
Using stencil cli, run stencil init
Using stencil cli run stencil start
Get error

**Comment by BC-krasnoshapka** [comment]
hi @Ctucker9233 , you need to run `npm install` before `stencil start`, as mentioned in the [documentation](https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/live-previewing-a-theme#installing-theme-modules).

**Comment by BC-krasnoshapka** [comment]
> @BC-krasnoshapka Inside the theme folder?

Yes

**Comment by Ctucker9233** [comment]
@BC-krasnoshapka Thank you. That seems to have solved it. I'm closing this.
