### ISSUE TITLE
Invoice wording doesn't change when changing template

### ISSUE THREAD

**Issue by jsfan** [bigcommerce/cornerstone#2401]
### Expected behavior
When modifying the file `templates/pages/account/orders/invoice.html`, I expect my invoices to change.

### Actual behavior
No modification of `templates/pages/account/orders/invoice.html` seems to have any impact on my invoices.

### Steps to reproduce behavior
1. Make any change to `templates/pages/account/orders/invoice.html`.
2. Apply changes.
3. Generate invoice for an order.

I realise that this may not be a bug in the theme but an issue with Bigcommerce itself. However, [asking about it in the community forums](https://support.bigcommerce.com/s/question/0D54v00009UpCZBCA3/how-do-i-make-changes-to-the-printable-invoice) did not get me any response. As the file I'm modifying looks like the one that is used for my invoices, I expect modifications to impact my invoices. If the file doesn't actually serve that purpose, it would be good to have a README somewhere that explains what purpose this file actually serves.

**Comment by BC-krasnoshapka** [comment]
hi @jsfan ,
`templates/pages/account/orders/invoice.html` is template responsible for rendering invoice from shopper account section on the storefront. But I guess your request is related to invoice that comes with order email. If so this is not right channel to ask, please contact our support team from Control Panel. Here are few relevant links as well:
[Customizing Invoices](https://developer.bigcommerce.com/docs/store-operations/orders/invoice-templates)
[Customizing the Invoice Email](https://support.bigcommerce.com/s/article/Invoices?language=en_US#custom)
