### ISSUE TITLE
Mobile Menu

### ISSUE THREAD

**Issue by ghost** [bigcommerce/cornerstone#782]
BC Team, I am not sure of this is something with our store setup.. After bootstrapping the Stencil development environment and starting the local dev server, the mobile menu of the default Stencil theme appears to be broken or empty. How do we populate that menu?

**Comment by hegrec** [comment]
Hello, please post your question to the developer portal help section where it will have more visibility and a developer can reach out to you. https://developer.bigcommerce.com/help/

Cheers
