### ISSUE TITLE
Navigation Menu

### ISSUE THREAD

**Issue by rickberg82** [bigcommerce/cornerstone#962]
Is there anyway to allow for the choice of making the main menu navigation a hover rather than click?  Also, when adding menu categories and subcategories the dropdown main navigation menu looks very unorganized, is there anyway that could be addressed so that it is condensed and fluid?  Here is my current site for reference: lake-life.com

Also, I attached a screenshot of the menu to show you what I mean.

Thank you,
![screen shot 2017-03-15 at 5 58 00 pm](https://cloud.githubusercontent.com/assets/20324218/23974379/f7e85e6c-09a8-11e7-9c96-38c6954cc20b.png)

**Comment by igogolev** [comment]
Any updates on this issue?

**Comment by bc-jcruiz** [comment]
@igogolev do you have a reference site?

**Comment by igogolev** [comment]
http://www.fevrie.com/

**Comment by bc-zoharmuzafi** [comment]
We are not planning to implement this feature on cornerstone at the moment. We recommend to submit the idea in the developers forum: https://support.bigcommerce.com/s/ideas
