### ISSUE TITLE
List View - Description - Fix Special Characters and Line Returns

### ISSUE THREAD

**Issue by GeorgeLondon** [bigcommerce/cornerstone#970]
Great to have a List View now, thanks (fixed in STENCIL-3194) - I've just activated it in our test store.

You can see from the below screenshot that special characters are not displaying correctly. Not using the H4 formatting is probably OK, but the line returns should be acknowledged - if not as returns, then with some kind of separator.

![image](https://cloud.githubusercontent.com/assets/26487893/24051730/f5a72498-0b2a-11e7-9180-7b63c6ddbd2f.png)

Second screenshot shows what that description looks like on the Product page with all of its formatted text intact. (Note - the product name "Kiwi Shoe Polish GSG" is further up the page offscreen in this screenshot, but it is displaying OK.)

![image](https://cloud.githubusercontent.com/assets/26487893/24051874/6ff52ca4-0b2b-11e7-855f-85a0a70e7dfc.png)

All screenshots from Win10/Chrome.

**Comment by bc-AlyssNoland** [comment]
For a quick fix, you just need to add an extra set of brackets around the description to properly escape html such as `{{{product.description}}}`

Thanks for the report!

**Comment by GeorgeLondon** [comment]
Thanks for your response. You're suggesting that I "add brackets" where?

**Comment by bc-AlyssNoland** [comment]
you'd need to add brackets around the summary, but you can see my fix linked above.

**Comment by GeorgeLondon** [comment]
Sorry - I don't really understand how this all works... so should your fix now be in the software?
I'm still seeing the same issue so either your fix hasn't been applied yet or isn't working.

I tried adding curly brackets to the product description but they were just displayed along with the rest of the text.

**Comment by GeorgeLondon** [comment]
OK - I found and edited the file at templates/components/products/list-item.html and that's fixed it. Hopefully this will be fixed in the next release of the theme. I very much appreciate your help.

Oh - do you not agree that the line-returns should be acknowledged in this view? I guess that's a design decision rather than necessarily a big... what's your opinion?

**Comment by bc-AlyssNoland** [comment]
@GeorgeLondon I personally don't feel that they should because this is meant to keep a uniform design, though I understand it can be confusing visually for a customer. It is really up to a priority of aesthetics and concisely presented information. 

For this theme, we are trying to make something agnostic that could be used by anyone or built upon.

**Comment by bc-AlyssNoland** [comment]
@GeorgeLondon my fix should be live relatively soon. You can check the changelog/releases for more info about when it'll be available or you can modify your theme to include it.
