### ISSUE TITLE
List View - Reinstate Quick View

### ISSUE THREAD

**Issue by GeorgeLondon** [bigcommerce/cornerstone#971]
Great to have a List View now, thanks (fixed in STENCIL-3194) - I've just activated it in our test store.

There is no 'Quick View' though.

Screenshot below from the Brands page, but is similar on Search and Categories pages.

![image](https://cloud.githubusercontent.com/assets/26487893/24053149/fac05026-0b2f-11e7-8ef1-2a027fdf1ae1.png)

Second screenshot is from grid view, with mouseover offering [Quick View] and [Choose Options].

![image](https://cloud.githubusercontent.com/assets/26487893/24053199/27a72786-0b30-11e7-8942-39594f381f9a.png)

All screenshots from Win10/Chrome.

**Comment by PreciselyAlyss** [comment]
Closing due to fix
