### ISSUE TITLE
Issue with Google recaptcha api script

### ISSUE THREAD

**Issue by minankmori** [bigcommerce/cornerstone#976]
Hello,

I am facing issue with the stencil theme, when enabling Captcha from the admin. we are getting random code in top of the product detail page. I found issue with script loding on product detail page for Recaptcha API. 

![error](https://cloud.githubusercontent.com/assets/26482645/24184659/1c5e9fb2-0ef5-11e7-8146-ee9523a7da20.JPG)

<script type="text/javascript" src="http://cdn6.bigcommerce.com/r-a2832a4688ce29764def846020ed5b29c4ced5ef/<script src="https://www.google.com/recaptcha/api.js" async defer></script>?cf708"></script>

Let me know anyone has a solution for this.

Thanks,
Minank Mori

**Comment by ocvninfo** [comment]
Same issue today

**Comment by bc-AlyssNoland** [comment]
@ocvninfo @minankmori We have a fix rolling out for this that should have it resolved later today (US time)

**Comment by bc-AlyssNoland** [comment]
@ocvninfo @minankmori This should be fixed. Can y'all verify?

**Comment by minankmori** [comment]
Yes, look like it has been fixed.
Thanks, @bc-AlyssNoland!

**Comment by ocvninfo** [comment]
@bc-AlyssNoland verified (y)
