### ISSUE TITLE
"Add to wishlist" adds product to default wishlist even when multiple wishlists exist

### ISSUE THREAD

**Issue by rollinxrose** [bigcommerce/cornerstone#977]
If you have multiple wish lists created under an account, it won't let you choose which list to add items to.  Items are only added to the first list.

**Comment by bc-AlyssNoland** [comment]
@rollinxrose Thanks for the report! This is currently a future-slated feature for wishlists in cornerstone. 

This is being tracked internally as STENCIL-2471

**Comment by ocvninfo** [comment]
Please add a confirmation to choose a wishlist to add item.

**Comment by mjschock** [comment]
closing this as you may now add to multiple wishlists :)
