### ISSUE TITLE
Write a Review is not working with quick view popup.

### ISSUE THREAD

**Issue by ocvninfo** [bigcommerce/cornerstone#984]
I found an issue when clicking Write a Review in quick view popup.
It will take me to product detail page but Write a Review popup is not showing up.

**Comment by bc-AlyssNoland** [comment]
@ocvninfo Can you provide steps to reproduce and any errors you might have gotten in the developer console?

**Comment by ocvninfo** [comment]
@bc-AlyssNoland 
Step 1: Go to Quick view any product
Step 2: in the quick view popup --> click Write a Review --> this will take you to product detail. However, Write review popup is not show up.

**Comment by mjschock** [comment]
thanks @ocvninfo 

@bc-AlyssNoland i've created a ticket [STENCIL-3352](https://jira.bigcommerce.com/browse/STENCIL-3352)

**Comment by ocvninfo** [comment]
thanks @mjschock (y)

**Comment by mjschock** [comment]
closing - fixed in #995
