### ISSUE TITLE
Stencil Theme Editor issue when choosing number of products.

### ISSUE THREAD

**Issue by ocvninfo** [bigcommerce/cornerstone#985]
Today, i have an issue when choosing Number of products (Featured, New, ...) to show at home page with Stencil Theme Editor on localhost.
I try to select Number of Featured Products is 10. But it's not working.

**Comment by bc-AlyssNoland** [comment]
@ocvninfo can you provide more details about the error you saw? or a screenshot?

**Comment by ocvninfo** [comment]
@bc-AlyssNoland 
Step 1: Go to Stencil Theme Editor
Step 2: In the Stencil Theme Editor, please try change Number of Featured products count select box.
When you selected a value, it is not allows you to refresh store

**Comment by PreciselyAlyss** [comment]
@ocvninfo this is currently working as expected for me. If you need to reopen, please do so.
