### ISSUE TITLE
tabs on product pages sometimes produce javascript errors (when loading non-cached theme-bundle.js)

### ISSUE THREAD

**Issue by acidburner** [bigcommerce/cornerstone#991]
### Expected behavior
Clicking on the tab items should switch views to that particular item.

### Actual behavior
Produces two types of javascript errors
Uncaught TypeError: Cannot read property 'is_hover" of undefined
Uncaught TypeError: Cannot read property 'deep_linking" of undefined
![image](https://cloud.githubusercontent.com/assets/11921939/24683837/81525b0a-1956-11e7-8dbf-ac89b837f831.png)

These javascript errors prevents the various tabs from displaying their content.

### Steps to reproduce behavior
1) Open incognito mode of a browser, open inspect console window
2) Goto http://cornerstone-light-demo.mybigcommerce.com/all/hand-salve/
3) Click the tabbed item 'Customers Also Viewed'

This is an intermittent issue that produces errors in console, as seen in screen shot. Some page refreshes issue happens, other times it does not.

**Chrome Version Information**
Version 57.0.2987.133

I've also experience this on my own custom theme using the Cornerstone theme as a base.

**Comment by funvill** [comment]
I am checkin in on the status of this issue? 
It's been a month with no updates from devs

**Comment by mcampa** [comment]
@funvill are you having this issue?

Is not happening for me on http://cornerstone-light-demo.mybigcommerce.com/all/hand-salve/. The tabs are working fine.

If you are having this issue, can you send me a link where this is happening?

**Comment by acidburner** [comment]
I'm unable to reproduce this issue on both [the cornerstone demo page](http://cornerstone-light-demo.mybigcommerce.com/all/hand-salve/), and my own custom template. 

This was still happening as of 3-4 weeks ago.

As far as I was ever able to tell, the bundle.js file was either never fully loading (since some bundled JS worked fine and others didn't), or outright failing to load, causing these JS errors.

If possible, I'd like a bit of clarity on what the issue was, and what fixed it, for my own sanity of course :P.

Thanks.

**Comment by mcampa** [comment]
Sorry but I don't have that information. I didn't see the bug happening on any store and I couldn't find a PR for the fix. So, I can't tell you what was the fix.
